### ISSUE TITLE
BUG with mekanism [ generate infinite resources ]

### ISSUE THREAD

**Issue by raffycaccia** [SuperMartijn642/Tesseract#1]
Video demostration
https://youtu.be/wo_V2BNLh_E

https://youtu.be/eED-SmwkXK8

**Comment by SuperMartijn642** [comment]
Are you using Minecraft 1.12?
What Forge, Tesseract and Mekanism versions are you using?
Does it work fine with others mods?

**Comment by raffycaccia** [comment]
Minecraft 1.15.2
Forge 31.2.0
Mekanism 1.15.2-9.10.6.419
Tesseract 1.0.5-mc1.15

I have not tested with other mods

**Comment by SuperMartijn642** [comment]
This seems to be a Mekanism issue.
[Using just Mekanism](https://youtu.be/R1yh6-18C7Y)

I reported it to Mekanism [here](https://github.com/mekanism/Mekanism/issues/6181)
