### ISSUE TITLE
1.16.1 Tesseract send/receive transfer issues

### ISSUE THREAD

**Issue by papaworld** [SuperMartijn642/Tesseract#10]
Hi, thank you for bringing back one of my favorite machine blocks... well done!

I created a test world for different spawning methods. One of them is Industrial Foregoing with fluid Essence.

Tesseract 1 (main) is sending energy, receiving items and fluids - works fine
Tesseract 2 (spawn system 1) is receiving energy, sending items and fluids - works fine
Tesseract 3 (spawn system 2) is receiving energy, sending items and fluids - will not send Items. Energy and Fluids ok.

Tried many different things like removing Tesseracts, deleted .nbt files, re-launch, etc. Same issue. Also, removed all Tesseracts, re-launch and place only Tesseract 1 and 3, same problem, won't send items from Tesseract 3. Then placed Tesseract 2, this one works ok.

The .nbt files register the 3 Tesseracts properly for energy, items and fluid with Tesseract designation 0,1,2 and properly registers the Name given for each.

It seems to not like its location? Each Tesseract is in it own chunk. Peculiar.

BTW: your recipe is just fine. Others that think it is not can use Craft Tweaker to adjust as they see fit.

**Comment by SuperMartijn642** [comment]
Could you maybe send a copy of the world (if it isn't too large) and a list of the mods you're using?
This would make it a lot easier to test for myself.

**Comment by papaworld** [comment]
The world is a test world for EXP to/from Industrial Foregoing Essence, so I am using custom Craft Tweaker Scripts and other supporting JSONs. I will make a simpler world and check to see if the problem can be replicated. I'll let you know.

**Comment by SuperMartijn642** [comment]
Closed due to inactivity.
