### ISSUE TITLE
[Question] ...

### ISSUE THREAD

**Issue by Dxnyy** [SuperMartijn642/Tesseract#101]
**Question**
...
I'd like to know if somehow I can remove the item transport and make the tesseract works only as tank and energy

**Comment by Dxnyy** [comment]
Im trying to use the mod for my modpack but i want force ppl using item transfer with something else and i'd like to block tesseract from it

**Comment by SuperMartijn642** [comment]
That is not possible currently.

**Comment by Dxnyy** [comment]
Ok, I really appreciate ur answer... hope u'll consider as idea ^^
