### ISSUE TITLE
Server crash 1.16.1 Exception in server tick loop

### ISSUE THREAD

**Issue by Bannta** [SuperMartijn642/Tesseract#12]
tesseract-1.0.11-mc1.16
Started a overworld to overword link after about 30mins, I believe another player started setting up one, I believe from neither to overworld, That is when the server started crashing on log in. The world was moved to single-player for Troubleshooting in which the crash log pointed out your mod as the fault. 
SilentMechanisms-1.16.1-0.8.1+62(Pump) --> LargeFluidTank-16.0.2 (fluid pipe) ->tesseract-1.0.11-mc1.16(tesseract) <=> tesseract -> LargeFluidTank-16.0.2 (fluid pipe) -> LargeFluidTank-16.0.2 (tank) ->refinedstorage-1.9.2(input data cable) 
Server Error: Description: Exception in server tick loop
Single Save: Description: Tesselating block model
[crash-2020-08-12_16.59.08-server.txt](https://github.com/SuperMartijn642/Tesseract/files/5069373/crash-2020-08-12_16.59.08-server.txt)
[crash-2020-08-12_23.43.12-client.txt](https://github.com/SuperMartijn642/Tesseract/files/5069380/crash-2020-08-12_23.43.12-client.txt)

Let me know if you need anything else? 
http://api.technicpack.net/modpack/hopcraft-1161 
running forge-1.16.1-32.0.108
to repeat add tesseract-1.0.11-mc1.16 to mods. Then build two independent(different channels)  set of tesseract(one overworld to overworld) and one nether to overworld.

**Comment by SuperMartijn642** [comment]
When I transfer fluids through the tesseract from the nether to the overworld using Large Fluid Tank's tanks and cables it works just fine, even when there are other tesseracts on different channels.
I also don't see any reference to code from Tesseract in the stacktrace of either report.

The server crash seems to come from Silent's Mechanisms.
The client crash seems to come from rendering a Refined Storage disk drive.

**Comment by Bannta** [comment]
ahh, then conflict with probably with Silent's Mechanisms, best guess. I had you mod installed for at least a day, but we didn't start using it up to the crash. when a person logged the server would crash. I moved the server to a single player client, same thing, crash on login. The Client crash log showed you mod, so I removed it and all is well now.

**Comment by SuperMartijn642** [comment]
Looking more into it, I think you might have sent me the wrong client crash report, because Tesseract isn't even loaded. The word 'tesseract' doesn't even appear in the report.

**Comment by Bannta** [comment]
https://github.com/SuperMartijn642/Tesseract/files/5069380/crash-2020-08-12_23.43.12-client.txt
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 8/12/20 11:43 PM
Description: **Tesselating** block model
...
oh it is "**Tesse**lating", I assume it was Tesseract because of the root word

**Comment by SuperMartijn642** [comment]
'Tesselating' is mapping a texture to a geometric plane in computer graphics, so 'tesselating' is not related to Tesseract. 😄

**Comment by SuperMartijn642** [comment]
I'll close the issue then

**Comment by Bannta** [comment]
you can close it. However, when I pull your mod off, my server stops crashing. So I suspect a conflict with the silent or the pipe mods I'm using.
