### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Rakorium80** [SuperMartijn642/Tesseract#16]
Hello,

I go to the Tesseract and when I scroll down and select the name I get the following error message

The game crashed whilst updating screen events
Error: java.lang.IndexOutOfBoundsException: Index: 16, Size: 15
Exit Code: -1

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at java.util.Collections$UnmodifiableList.get(Unknown Source)
	at com.supermartijn642.tesseract.screen.TesseractScreen.func_73864_a(TesseractScreen.java:283)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.supermartijn642.tesseract.screen.TesseractScreen.func_146274_d(TesseractScreen.java:340)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.supermartijn642.tesseract.screen.TesseractScreen

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Rakorium80'/10265939, l='MpServer', x=5027.49, y=48.00, z=-1475.09], EntityOtherPlayerMP['Blighthammer'/8001565, l='MpServer', x=5013.60, y=69.00, z=-1459.59]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (281,64,99), Chunk: (at 9,4,3 in 17,6; contains blocks 272,0,96 to 287,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 298288098 game time, 1720450 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 239 total; [EntityItem['item.item.exoticbirds.cardinal_egg'/10230420, l='MpServer', x=4998.84, y=68.00, z=-1515.96], EntityCreeper['Creeper'/7797886, l='MpServer', x=5022.81, y=58.00, z=-1482.53], EntitySkeleton['Skelett'/10208912, l='MpServer', x=5058.50, y=19.00, z=-1492.50], EntitySpider['Spinne'/10292883, l='MpServer', x=5050.50, y=12.00, z=-1504.50], EntitySpider['Spinne'/10296970, l='MpServer', x=5028.50, y=69.00, z=-1508.50], MoCEntityHippoTang['HippoTang'/6682, l='MpServer', x=4953.47, y=61.80, z=-1395.22], EntitySheep['Schaf'/6171, l='MpServer', x=5030.45, y=77.00, z=-1529.89], EntityHorse['Pferd'/6172, l='MpServer', x=5029.13, y=79.00, z=-1534.96], EntityMagpie['Magpie'/6173, l='MpServer', x=5033.83, y=79.00, z=-1533.25], EntityRobin['Robin'/6176, l='MpServer', x=5047.43, y=79.00, z=-1538.40], EntityCreeper['Creeper'/10297021, l='MpServer', x=5033.50, y=41.00, z=-1546.50], EntityMagpie['Magpie'/6177, l='MpServer', x=5048.97, y=80.00, z=-1534.34], EntityButterfly['Papilio troilus'/5534833, l='MpServer', x=5033.14, y=68.00, z=-1457.86], EntityBabySkeleton['Baby-Skelett'/10244795, l='MpServer', x=5032.50, y=18.00, z=-1510.50], MoCEntityBass['Bass'/6697, l='MpServer', x=4953.70, y=61.00, z=-1409.52], MoCEntityMaggot['Maggot'/6189, l='MpServer', x=5077.17, y=68.00, z=-1466.33], EntityBabySkeleton['Baby-Skelett'/10269869, l='MpServer', x=5036.60, y=49.00, z=-1463.45], EntityCartChest['Güterwaggon'/1569835, l='MpServer', x=5115.50, y=10.06, z=-1590.50], EntityChickensChicken['Holzstammhuhn'/6208, l='MpServer', x=5017.24, y=20.00, z=-1523.51], EntityCartChest['Güterwaggon'/6722, l='MpServer', x=4950.50, y=40.06, z=-1434.49], MoCEntitySnail['Snail'/6210, l='MpServer', x=5017.49, y=68.00, z=-1524.75], EntityCreeper['Creeper'/10294481, l='MpServer', x=5019.18, y=36.00, z=-1501.02], EntityItem['item.item.string'/10141908, l='MpServer', x=5014.28, y=31.00, z=-1527.07], EntityPlayerSP['Rakorium80'/10265939, l='MpServer', x=5027.49, y=48.00, z=-1475.09], EntityRobin['Robin'/6735, l='MpServer', x=5030.58, y=78.00, z=-1533.10], EntityCreeper['Creeper'/10294482, l='MpServer', x=5022.47, y=36.00, z=-1499.84], EntityPigeon['Pigeon'/6736, l='MpServer', x=5038.91, y=80.00, z=-1538.83], EntityCardinal['Cardinal'/6740, l='MpServer', x=4999.24, y=68.00, z=-1516.83], MoCEntitySnail['Snail'/6741, l='MpServer', x=5001.60, y=68.00, z=-1502.88], MoCEntityGoat['Goat'/6742, l='MpServer', x=4998.20, y=68.00, z=-1514.56], EntityZombie['Zombie'/10289860, l='MpServer', x=5011.50, y=69.00, z=-1539.50], EntityItem['item.item.string'/10139329, l='MpServer', x=5073.88, y=56.00, z=-1479.29], EntityZombie['Zombie'/10289858, l='MpServer', x=4999.55, y=19.00, z=-1554.74], EntityItem['item.tile.log.oak'/10161918, l='MpServer', x=5017.76, y=20.00, z=-1523.88], EntityOtherPlayerMP['Blighthammer'/8001565, l='MpServer', x=5013.60, y=69.00, z=-1459.59], EntityZombie['Zombie'/10294001, l='MpServer', x=5028.50, y=65.00, z=-1508.50], EntitySpider['Spinne'/10313452, l='MpServer', x=5014.50, y=37.00, z=-1524.50], EntityCartChest['Güterwaggon'/6772, l='MpServer', x=5116.50, y=16.00, z=-1530.88], EntityHorse['Pferd'/6774, l='MpServer', x=5104.47, y=87.00, z=-1535.56], EntityHorse['Pferd'/6777, l='MpServer', x=5105.81, y=87.00, z=-1546.12], EntityHorse['Pferd'/6778, l='MpServer', x=5102.52, y=87.00, z=-1543.59], EntityHorse['Pferd'/6782, l='MpServer', x=5092.33, y=86.00, z=-1532.50], EntityZombie['Zombie'/10287842, l='MpServer', x=5098.50, y=20.00, z=-1435.50], EntitySheep['Schaf'/6783, l='MpServer', x=5093.77, y=86.00, z=-1535.27], MoCEntityMaggot['Maggot'/6272, l='MpServer', x=5039.21, y=68.00, z=-1451.88], EntityItemFrame['Rahmen'/6273, l='MpServer', x=5061.97, y=59.50, z=-1489.50], EntityCreeper['Creeper'/10276381, l='MpServer', x=5082.50, y=67.00, z=-1460.50], EntityItemFrame['Rahmen'/6274, l='MpServer', x=5061.97, y=59.50, z=-1491.50], EntityItemFrame['Rahmen'/6275, l='MpServer', x=5061.97, y=61.50, z=-1491.50], EntityItemFrame['Rahmen'/6276, l='MpServer', x=5061.97, y=59.50, z=-1495.50], EntityItemFrame['Rahmen'/6277, l='MpServer', x=5061.97, y=59.50, z=-1497.50], EntityItemFrame['Rahmen'/6278, l='MpServer', x=5061.97, y=59.50, z=-1493.50], EntityItemFrame['Rahmen'/6279, l='MpServer', x=5061.97, y=61.50, z=-1489.50], EntityItemFrame['Rahmen'/6280, l='MpServer', x=5061.97, y=61.50, z=-1497.50], EntityItemFrame['Rahmen'/6281, l='MpServer', x=5061.97, y=61.50, z=-1495.50], EntityItemFrame['Rahmen'/6282, l='MpServer', x=5059.03, y=61.50, z=-1501.50], EntityOtherPlayerMP['Blighthammer'/8001565, l='MpServer', x=5013.60, y=69.00, z=-1459.59], EntityItemFrame['Rahmen'/6283, l='MpServer', x=5061.97, y=61.50, z=-1493.50], EntityItemFrame['Rahmen'/6287, l='MpServer', x=5061.97, y=59.50, z=-1487.50], EntityCow['Kuh'/6799, l='MpServer', x=5101.24, y=86.00, z=-1551.35], EntityItemFrame['Rahmen'/6288, l='MpServer', x=5061.97, y=59.50, z=-1485.50], EntityHorse['Pferd'/6800, l='MpServer', x=5080.51, y=78.54, z=-1530.35], EntityItemFrame['Rahmen'/6289, l='MpServer', x=5059.03, y=61.50, z=-1483.50], EntityItemFrame['Rahmen'/6290, l='MpServer', x=5061.97, y=61.50, z=-1487.50], EntityItemFrame['Rahmen'/6291, l='MpServer', x=5061.97, y=59.50, z=-1483.50], EntityItemFrame['Rahmen'/6292, l='MpServer', x=5061.97, y=61.50, z=-1485.50], EntityItemFrame['Rahmen'/6293, l='MpServer', x=5059.03, y=61.50, z=-1487.50], EntityItemFrame['Rahmen'/6294, l='MpServer', x=5059.03, y=59.50, z=-1487.50], EntityItemFrame['Rahmen'/6295, l='MpServer', x=5059.03, y=61.50, z=-1485.50], EntityItemFrame['Rahmen'/6296, l='MpServer', x=5059.03, y=59.50, z=-1485.50], EntityZombie['Zombie'/10262533, l='MpServer', x=5003.50, y=18.00, z=-1479.50], EntityItemFrame['Rahmen'/6297, l='MpServer', x=5059.03, y=59.50, z=-1483.50], EntityOwl['Owl'/6298, l='MpServer', x=5084.24, y=84.00, z=-1512.56], EntityCow['Kuh'/6301, l='MpServer', x=5084.86, y=85.00, z=-1503.55], EntityOwl['Owl'/6302, l='MpServer', x=5085.67, y=85.00, z=-1503.32], EntityButterfly['C-Falter'/9959462, l='MpServer', x=4980.29, y=75.00, z=-1458.46], EntityItem['item.item.exoticbirds.robin_egg'/10161710, l='MpServer', x=5030.01, y=78.00, z=-1533.74], MoCEntityMaggot['Maggot'/6337, l='MpServer', x=5028.12, y=68.00, z=-1447.51], EntityArmorStand['Rüstungsständer'/6339, l='MpServer', x=5049.50, y=58.00, z=-1442.50], EntityArmorStand['Rüstungsständer'/6340, l='MpServer', x=5049.50, y=58.00, z=-1444.50], EntityGlyph['entity.openblocks.glyph.name'/6341, l='MpServer', x=5049.98, y=61.50, z=-1444.50], EntityGlyph['entity.openblocks.glyph.name'/6342, l='MpServer', x=5049.98, y=61.50, z=-1442.50], EntityZombieVillager['Dorfbewohnerzombie'/10260058, l='MpServer', x=5060.50, y=62.00, z=-1554.50], EntityGlyph['entity.openblocks.glyph.name'/6344, l='MpServer', x=5038.98, y=60.44, z=-1431.50], EntityGlyph['entity.openblocks.glyph.name'/6345, l='MpServer', x=5038.98, y=60.50, z=-1429.50], EntityItem['item.item.dyePowder.silver'/10204242, l='MpServer', x=5044.13, y=58.00, z=-1476.65], EntityZombieVillager['Dorfbewohnerzombie'/10269766, l='MpServer', x=5002.52, y=27.00, z=-1537.71], EntityCartChest['Güterwaggon'/6362, l='MpServer', x=5008.50, y=20.06, z=-1495.50], EntityBabySkeleton['Baby-Skelett'/10228291, l='MpServer', x=4983.50, y=24.00, z=-1425.50], EntityCartChest['Güterwaggon'/6370, l='MpServer', x=5071.50, y=17.06, z=-1524.56], EntityHorse['Pferd'/6371, l='MpServer', x=5069.04, y=80.00, z=-1530.73], EntityCartChest['Güterwaggon'/6886, l='MpServer', x=5144.51, y=20.00, z=-1402.22], EntityItem['item.item.hatchery.chickenmanure'/10127984, l='MpServer', x=5016.36, y=20.00, z=-1523.20], EntityItem['item.item.exoticbirds.flamingo_egg'/10210410, l='MpServer', x=4967.10, y=68.00, z=-1513.15], EntityCartChest['Güterwaggon'/6899, l='MpServer', x=5108.50, y=19.06, z=-1389.49], EntityBrainyZombie['Angry Zombie'/10262118, l='MpServer', x=4995.50, y=29.00, z=-1457.50], EntityCartChest['Güterwaggon'/6907, l='MpServer', x=5129.51, y=18.00, z=-1438.99], EntityCartChest['Güterwaggon'/6908, l='MpServer', x=5129.50, y=18.00, z=-1430.31], MoCEntityMaggot['Maggot'/6401, l='MpServer', x=4968.47, y=68.00, z=-1471.97], EntityCartChest['Güterwaggon'/6926, l='MpServer', x=5149.50, y=20.00, z=-1379.28], MoCEntityBass['Bass'/6415, l='MpServer', x=4965.70, y=62.00, z=-1405.70], EntityCartChest['Güterwaggon'/6422, l='MpServer', x=4990.50, y=19.06, z=-1498.50], EntityItemFrame['Rahmen'/5910, l='MpServer', x=5037.97, y=61.50, z=-1485.50], EntityCartChest['Güterwaggon'/6936, l='MpServer', x=5136.50, y=14.06, z=-1548.50], MoCEntityMaggot['Maggot'/6429, l='MpServer', x=4990.78, y=68.00, z=-1426.18], MoCEntityMaggot['Maggot'/6430, l='MpServer', x=4988.73, y=68.00, z=-1429.51], EntityCartChest['Güterwaggon'/6432, l='MpServer', x=4988.29, y=19.00, z=-1418.51], EntityZombie['Zombie'/10303929, l='MpServer', x=4973.65, y=69.00, z=-1423.20], MoCEntityMaggot['Maggot'/6439, l='MpServer', x=4995.52, y=68.00, z=-1430.59], MoCEntityMaggot['Maggot'/6440, l='MpServer', x=4989.13, y=68.00, z=-1429.49], EntityCartChest['Güterwaggon'/6443, l='MpServer', x=5012.50, y=18.06, z=-1453.50], EntityBabySkeleton['Baby-Skelett'/10306998, l='MpServer', x=4979.50, y=23.00, z=-1476.50], EntitySheep['Schaf'/6444, l='MpServer', x=5018.00, y=68.00, z=-1438.95], EntityItemFrame['Rahmen'/5932, l='MpServer', x=5041.03, y=61.50, z=-1483.50], EntitySheep['Schaf'/6445, l='MpServer', x=5018.02, y=68.00, z=-1440.93], EntityItemFrame['Rahmen'/5933, l='MpServer', x=5047.03, y=61.50, z=-1483.50], EntitySheep['Schaf'/6446, l='MpServer', x=5017.65, y=68.00, z=-1433.83], EntityItemFrame['Rahmen'/5934, l='MpServer', x=5043.97, y=61.50, z=-1485.50], EntityLlama['Lama'/6447, l='MpServer', x=5017.07, y=68.00, z=-1440.10], EntityItemFrame['Rahmen'/5935, l='MpServer', x=5049.97, y=59.50, z=-1485.50], EntityCartChest['Güterwaggon'/6448, l='MpServer', x=5012.50, y=13.06, z=-1367.49], EntityItemFrame['Rahmen'/5936, l='MpServer', x=5041.03, y=59.50, z=-1487.50], EntityItemFrame['Rahmen'/5937, l='MpServer', x=5041.03, y=61.50, z=-1487.50], EntityItemFrame['Rahmen'/5938, l='MpServer', x=5041.03, y=59.50, z=-1483.50], EntityItemFrame['Rahmen'/5939, l='MpServer', x=5043.97, y=59.50, z=-1483.50], EntityItemFrame['Rahmen'/5940, l='MpServer', x=5043.97, y=59.50, z=-1487.50], EntityItemFrame['Rahmen'/5941, l='MpServer', x=5043.97, y=59.50, z=-1485.50], EntityItemFrame['Rahmen'/5942, l='MpServer', x=5049.97, y=61.50, z=-1483.50], EntityItemFrame['Rahmen'/5943, l='MpServer', x=5049.97, y=61.50, z=-1485.50], EntityItemFrame['Rahmen'/5944, l='MpServer', x=5043.97, y=61.50, z=-1483.50], EntityCreeper['Creeper'/10306469, l='MpServer', x=5090.50, y=66.00, z=-1457.50], EntityItemFrame['Rahmen'/5945, l='MpServer', x=5049.97, y=59.50, z=-1487.50], EntityCartChest['Güterwaggon'/6457, l='MpServer', x=5063.51, y=20.00, z=-1367.51], EntityItemFrame['Rahmen'/5946, l='MpServer', x=5041.03, y=61.50, z=-1485.50], EntityItem['item.item.string'/10173856, l='MpServer', x=5013.13, y=70.00, z=-1533.63], EntityItemFrame['Rahmen'/5947, l='MpServer', x=5041.03, y=59.50, z=-1485.50], EntityItemFrame['Rahmen'/5948, l='MpServer', x=5043.97, y=61.50, z=-1487.50], EntityItemFrame['Rahmen'/5949, l='MpServer', x=5049.97, y=59.50, z=-1483.50], MoCEntityTiger['Tiger'/6461, l='MpServer', x=5083.01, y=62.00, z=-1397.84], EntityItemFrame['Rahmen'/5950, l='MpServer', x=5049.97, y=61.50, z=-1487.50], EntityItemFrame['Rahmen'/5951, l='MpServer', x=5055.97, y=61.50, z=-1487.50], EntityItemFrame['Rahmen'/5952, l='MpServer', x=5055.97, y=59.50, z=-1487.50], EntityItemFrame['Rahmen'/5953, l='MpServer', x=5055.97, y=61.50, z=-1485.50], EntityItemFrame['Rahmen'/5954, l='MpServer', x=5055.97, y=61.50, z=-1483.50], EntityItemFrame['Rahmen'/5955, l='MpServer', x=5055.97, y=59.50, z=-1485.50], EntityChickensChicken['Hellgraues Huhn'/5956, l='MpServer', x=5044.62, y=58.00, z=-1477.12], EntityItem['item.item.exoticbirds.robin_egg'/10205662, l='MpServer', x=5046.55, y=79.00, z=-1537.84], EntitySkeleton['Skelett'/10264025, l='MpServer', x=5065.50, y=83.00, z=-1509.50], EntityOwl['Owl'/6469, l='MpServer', x=5091.30, y=78.00, z=-1478.30], EntityCartChest['Güterwaggon'/6479, l='MpServer', x=5102.50, y=21.06, z=-1425.34], MoCEntityMaggot['Maggot'/6484, l='MpServer', x=5099.89, y=65.00, z=-1425.72], MoCEntityGoat['Goat'/6485, l='MpServer', x=5101.60, y=67.00, z=-1403.76], MoCEntityMole['Mole'/6493, l='MpServer', x=5100.95, y=67.00, z=-1396.12], EntitySpider['Spinne'/10282492, l='MpServer', x=5022.50, y=20.00, z=-1553.50], EntityBabySkeleton['Baby-Skelett'/10297845, l='MpServer', x=4963.50, y=20.00, z=-1457.50], EntityItem['item.item.exoticbirds.magpie_egg'/10158056, l='MpServer', x=5049.46, y=80.00, z=-1533.79], EntityZombie['Zombie'/10288618, l='MpServer', x=5018.50, y=34.00, z=-1507.50], MoCEntityMaggot['Maggot'/6011, l='MpServer', x=5015.99, y=68.00, z=-1509.43], EntityButterfly['Kleiner Kohlweißling'/8715256, l='MpServer', x=4995.48, y=68.03, z=-1436.77], EntityItem['item.item.string'/10116580, l='MpServer', x=5083.57, y=44.00, z=-1459.36], EntityItemFrame['Rahmen'/6017, l='MpServer', x=5037.97, y=61.50, z=-1501.50], EntityItemFrame['Rahmen'/6018, l='MpServer', x=5037.97, y=59.50, z=-1489.50], EntityItemFrame['Rahmen'/6019, l='MpServer', x=5037.97, y=59.50, z=-1491.50], EntityItemFrame['Rahmen'/6020, l='MpServer', x=5037.97, y=59.50, z=-1499.50], EntityItemFrame['Rahmen'/6021, l='MpServer', x=5037.97, y=59.50, z=-1497.50], EntityItemFrame['Rahmen'/6022, l='MpServer', x=5037.97, y=59.50, z=-1495.50], MoCEntitySnail['Snail'/6023, l='MpServer', x=5053.43, y=81.00, z=-1516.60], EntityCartChest['Güterwaggon'/6024, l='MpServer', x=5055.50, y=22.06, z=-1500.51], EntityItemFrame['Rahmen'/6026, l='MpServer', x=5043.97, y=59.50, z=-1495.50], EntityItemFrame['Rahmen'/6027, l='MpServer', x=5043.97, y=61.50, z=-1489.50], EntityZombie['Zombie'/10280208, l='MpServer', x=5036.50, y=35.00, z=-1534.50], EntityItemFrame['Rahmen'/6028, l='MpServer', x=5043.97, y=59.50, z=-1491.50], EntityItemFrame['Rahmen'/6029, l='MpServer', x=5043.97, y=61.50, z=-1491.50], EntityItemFrame['Rahmen'/6030, l='MpServer', x=5041.03, y=59.50, z=-1491.50], EntityItemFrame['Rahmen'/6031, l='MpServer', x=5041.03, y=61.50, z=-1491.50], EntityItemFrame['Rahmen'/6032, l='MpServer', x=5041.03, y=61.50, z=-1499.50], EntityItemFrame['Rahmen'/6033, l='MpServer', x=5041.03, y=61.50, z=-1501.50], EntityItemFrame['Rahmen'/6034, l='MpServer', x=5049.97, y=61.50, z=-1489.50], EntityItemFrame['Rahmen'/6035, l='MpServer', x=5043.97, y=61.50, z=-1499.50], EntityItemFrame['Rahmen'/6036, l='MpServer', x=5043.97, y=61.50, z=-1497.50], EntityItemFrame['Rahmen'/6037, l='MpServer', x=5043.97, y=59.50, z=-1489.50], EntityItemFrame['Rahmen'/6038, l='MpServer', x=5041.03, y=59.50, z=-1493.50], EntityItemFrame['Rahmen'/6039, l='MpServer', x=5041.03, y=59.50, z=-1489.50], EntityItemFrame['Rahmen'/6040, l='MpServer', x=5043.97, y=61.50, z=-1495.50], EntityItemFrame['Rahmen'/6041, l='MpServer', x=5041.03, y=61.50, z=-1489.50], EntityItemFrame['Rahmen'/6042, l='MpServer', x=5043.97, y=61.50, z=-1493.50], EntityItem['item.item.exoticbirds.owl_egg'/10089731, l='MpServer', x=5085.48, y=85.00, z=-1502.63], MoCEntitySnail['Snail'/6555, l='MpServer', x=5002.89, y=68.00, z=-1524.05], EntityItemFrame['Rahmen'/6043, l='MpServer', x=5041.03, y=61.50, z=-1493.50], MoCEntitySnail['Snail'/6556, l='MpServer', x=5004.42, y=68.00, z=-1520.39], EntityItemFrame['Rahmen'/6044, l='MpServer', x=5041.03, y=61.50, z=-1495.50], MoCEntityBunny['Bunny'/6557, l='MpServer', x=5006.53, y=68.00, z=-1532.27], EntityItemFrame['Rahmen'/6045, l='MpServer', x=5041.03, y=61.50, z=-1497.50], MoCEntityAnt['Ant'/6558, l='MpServer', x=5018.52, y=77.00, z=-1551.51], EntityItemFrame['Rahmen'/6046, l='MpServer', x=5041.03, y=59.50, z=-1495.50], EntityItemFrame['Rahmen'/6047, l='MpServer', x=5041.03, y=59.50, z=-1497.50], EntityItemFrame['Rahmen'/6048, l='MpServer', x=5041.03, y=59.50, z=-1501.50], EntityItemFrame['Rahmen'/6049, l='MpServer', x=5041.03, y=59.50, z=-1499.50], EntityZombie['Zombie'/10280765, l='MpServer', x=5081.50, y=55.00, z=-1458.50], EntityItemFrame['Rahmen'/6050, l='MpServer', x=5043.97, y=59.50, z=-1501.50], EntityItemFrame['Rahmen'/6051, l='MpServer', x=5043.97, y=61.50, z=-1501.50], EntityItemFrame['Rahmen'/6052, l='MpServer', x=5043.97, y=59.50, z=-1499.50], EntityItemFrame['Rahmen'/6053, l='MpServer', x=5043.97, y=59.50, z=-1497.50], EntityItemFrame['Rahmen'/6054, l='MpServer', x=5043.97, y=59.50, z=-1493.50], EntityItemFrame['Rahmen'/6055, l='MpServer', x=5049.97, y=59.50, z=-1489.50], EntityItemFrame['Rahmen'/6056, l='MpServer', x=5055.97, y=61.50, z=-1489.50], EntityItemFrame['Rahmen'/6057, l='MpServer', x=5055.97, y=59.50, z=-1489.50], MoCEntityMaggot['Maggot'/6570, l='MpServer', x=4950.47, y=68.00, z=-1458.85], EntityItemFrame['Rahmen'/6058, l='MpServer', x=5055.97, y=61.50, z=-1491.50], EntityItemFrame['Rahmen'/6059, l='MpServer', x=5055.97, y=59.50, z=-1491.50], EntityItemFrame['Rahmen'/6060, l='MpServer', x=5055.97, y=61.50, z=-1493.50], EntityItemFrame['Rahmen'/6061, l='MpServer', x=5055.97, y=59.50, z=-1493.50], EntityItemFrame['Rahmen'/6062, l='MpServer', x=5055.97, y=61.50, z=-1495.50], EntityItemFrame['Rahmen'/6063, l='MpServer', x=5055.97, y=59.50, z=-1495.50], EntityItemFrame['Rahmen'/6064, l='MpServer', x=5055.97, y=61.50, z=-1497.50], EntityItemFrame['Rahmen'/6065, l='MpServer', x=5055.97, y=59.50, z=-1497.50], EntityItemFrame['Rahmen'/6066, l='MpServer', x=5055.97, y=61.50, z=-1499.50], EntityItemFrame['Rahmen'/6067, l='MpServer', x=5055.97, y=59.50, z=-1499.50], EntityItemFrame['Rahmen'/6068, l='MpServer', x=5055.97, y=61.50, z=-1501.50], EntityItemFrame['Rahmen'/6069, l='MpServer', x=5055.97, y=59.50, z=-1501.50], MoCEntityPanther['Panther'/6585, l='MpServer', x=4972.97, y=68.00, z=-1520.91], EntitySkeleton['Skelett'/10279205, l='MpServer', x=5061.27, y=76.00, z=-1546.48], MoCEntitySnail['Snail'/6586, l='MpServer', x=4993.02, y=67.00, z=-1548.47], EntityCreeper['Creeper'/10252070, l='MpServer', x=5102.50, y=36.00, z=-1451.50], MoCEntitySnake['Snake'/6587, l='MpServer', x=5003.73, y=67.00, z=-1542.18], MoCEntityGoat['Goat'/6588, l='MpServer', x=4951.60, y=63.00, z=-1502.50], EntityFlamingo['Flamingo'/6591, l='MpServer', x=4966.46, y=68.00, z=-1513.20], EntityCreeper['Creeper'/10205017, l='MpServer', x=5065.50, y=58.00, z=-1504.50], EntityCreeper['Creeper'/10145098, l='MpServer', x=4973.50, y=53.00, z=-1439.50], EntitySpider['Spinne'/10260812, l='MpServer', x=5095.50, y=85.00, z=-1519.50], EntityButterfly['Kaiser I Hind'/9625926, l='MpServer', x=4981.25, y=77.00, z=-1457.44], EntityItem['item.item.string'/10171768, l='MpServer', x=5019.88, y=22.00, z=-1529.30], EntitySkeleton['Skelett'/10264949, l='MpServer', x=4958.50, y=39.00, z=-1463.50], EntityCartChest['Güterwaggon'/1609707, l='MpServer', x=5025.50, y=15.06, z=-1333.50], EntityCartChest['Güterwaggon'/6647, l='MpServer', x=4932.50, y=41.06, z=-1505.51], EntityCreeper['Creeper'/10226533, l='MpServer', x=5101.50, y=22.00, z=-1437.50], MoCEntitySnake['Snake'/6650, l='MpServer', x=4948.84, y=68.00, z=-1525.97], EntityItem['item.item.exoticbirds.owl_egg'/10113376, l='MpServer', x=5083.53, y=84.00, z=-1511.71], EntitySkeleton['Skelett'/10302306, l='MpServer', x=5045.50, y=14.00, z=-1499.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by SuperMartijn642** [comment]
What version of Minecraft, Forge and Tesseract are you using?

**Comment by Rakorium80** [comment]
Hi 👋 



I was able to delete all the names again because of the length it couldn't have been. maybe because I used spaces

Von meinem iPhone gesendet

**Comment by SuperMartijn642** [comment]
I will look into it, but I need to know what Minecraft version this happened on?
I have different code for different versions of minecraft so I need to know what version it is. I don't have the time to test on all of them.

**Comment by Rakorium80** [comment]
Mc version 1.12.2

Von meinem iPhone gesendet

**Comment by SuperMartijn642** [comment]
I found the issue. When there are a lot of channels, you scroll down the list of channels and click one of the last ones, the game would crash. I fixed it now in version 1.0.13.

Thank you for the report!
