### ISSUE TITLE
[Feature] ... Mekanism support?

### ISSUE THREAD

**Issue by Devalut** [SuperMartijn642/Tesseract#18]
Noticed Mekanism cables do not interact, writing to santa for support.

**Comment by SuperMartijn642** [comment]
Tesseract should already work fine with Mekanism, if not that's a bug.
Mekanism's energy and fluid cables should just work when connecting them at either end of the tesseracts.
The item cables need an inventory at one of the tesseracts, there's nothing I can do about that without putting a required dependency on Mekanism.

**Comment by SuperMartijn642** [comment]
I will close the issue, if you want to comment something I will reopen it.

**Comment by Devalut** [comment]
By all means, no worries

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
