### ISSUE TITLE
[Suggestion] [1.12.2] Add 1.7.10 Tesseract Recipe if Thermal Expansion is present

### ISSUE THREAD

**Issue by Irgendwer01** [SuperMartijn642/Tesseract#19]
Hello, it would be nice to see if it would be possible to add back the old 1.7.10 recipe for the Tesseract if Thermal Expansion is present through something like a Config option.

**Comment by SuperMartijn642** [comment]
I will have a look at doing this now that thermal mods are updated to the newer versions.

**Comment by Irgendwer01** [comment]
@SuperMartijn642 will it be only 1.14+ or will the recipe be in the 1.12.2 version too?

**Comment by SuperMartijn642** [comment]
If I add it, I'll add it for all versions of the mod. That includes 1.12.2.

**Comment by Irgendwer01** [comment]
ok, good luck with that :)

**Comment by Steven-OConnell** [comment]
Any news on this feature?
Using craft tweaker to make the recipe more difficult works and is an option, but you are limited in the crafting process complexity and Thermal Expansion offered a nice challenge by having a multi faceted process to acquiring a fully functional Tesseract.

**Comment by SuperMartijn642** [comment]
I don't want to add two extra items just for when Thermal Expansion is installed, so if I add it, it will likely just be a recipe with Thermal Expansion items instead of vanilla ones.

**Comment by Steven-OConnell** [comment]
That's fair.

**Comment by SuperMartijn642** [comment]
I added a config option to enable an alternative Thermal Series recipe now in version 1.0.22.

Thank you both for the suggestions!
