### ISSUE TITLE
Log spam from mekanism + tesseract

### ISSUE THREAD

**Issue by Sunekaer** [SuperMartijn642/Tesseract#2]
![image](https://user-images.githubusercontent.com/18720460/82739993-eabfd980-9d44-11ea-8e98-cd4a04cf887c.png)
From report at https://github.com/FTBTeam/FTB-Omnia/issues/97:
Issue: Log spam. I talked with mekanism dev, this is tesseract issue. Mekanism only warns about badly implemented inventory handler

tesseract-1.0.4-mc1.15
Minecraft Version: 1.15.2
forge-31.1.87

**Comment by SuperMartijn642** [comment]
I can't reproduce it, so I assume version 1.0.6 might have fixed it.
