### ISSUE TITLE
[Crash] Crash when opening screen 1.16.5

### ISSUE THREAD

**Issue by Shotguun29** [SuperMartijn642/Tesseract#25]
**Version Info**
- Minecraft, 1.16.5
- Tesseract, 
tesseract-1.0.19-mc1.16.5.jar

**Steps to Reproduce**
place tess, open gui click energy. crash

**Crash report (~/logs/latest.log)**
https://pastebin.com/HGpdhQde

**Comment by Shotguun29** [comment]
Note: crashes client not server

**Comment by SuperMartijn642** [comment]
Is this the entire crash report, because I thought it normally shows all the mods at the buttom?
What version of Core lib are you using?

**Comment by Shotguun29** [comment]
My apologizes, I didn't realize I didn't get the whole crash report. https://pastebin.com/KD6jJTp7 

supermartijn642corelib-1.0.4-mc1.16.5.jar

**Comment by SuperMartijn642** [comment]
Thank you, I think it should work now in version 1.0.20 of Tesseract.

**Comment by Shotguun29** [comment]
10/4 buddy.  thanks

**Comment by SuperMartijn642** [comment]
I will close the issue then.

Thank you for reporting it!
