### ISSUE TITLE
[Bug] Channel shows wrong username

### ISSUE THREAD

**Issue by TrickDevelopment** [SuperMartijn642/Tesseract#27]
**Version Info**
- Minecraft, 1.16.5
- Forge, 36.1.31
- Tesseract, tesseract-1.0.20-mc1.16.5

**Description of the Bug**
When I created a private channel, it said the person who created it as my previous minecraft account name. My current name is TrickPlayzMC, not trickbrain26. "This also happens with a public channel"

**Steps to Reproduce**
Have a minecraft account with a previous name, then create a private channel.

**Screenshots**
![2021-06-09_19 11 32](https://user-images.githubusercontent.com/85457129/121440847-b53d5c80-c956-11eb-9450-8e8f49d63836.png)
![2021-06-09_19 12 34](https://user-images.githubusercontent.com/85457129/121440849-b5d5f300-c956-11eb-8c9c-d02d608227b5.png)

**Comment by SuperMartijn642** [comment]
Whoops, I think I might be taking the oldest name then instead of the newest. 😅
Since it's not a critical bug, it might be a bit before I get to it.

**Comment by TrickDevelopment** [comment]
Itz fine i'll just make my channels public for now, but ty anyway

**Comment by SuperMartijn642** [comment]
It should show the correct username now in version 1.0.23.
