### ISSUE TITLE
[Bug] Yet another strange graphics bug but not game breaking

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SuperMartijn642/Tesseract#28]
Minecraft 1.12.2 Forge Final
supermartijn642corelib-1.0.7-mc1.12.jar
tesseract-1.0.21-mc1.12.jar

My head hurts but I care deeply about your project so here some screenshots for sure affects Pixelmon not sure if other mods are affected.

![2021-06-13_23 35 11](https://user-images.githubusercontent.com/10351221/121839844-9285ad80-cca0-11eb-9ff5-de1c2bee023a.png)
![2021-06-13_23 35 20](https://user-images.githubusercontent.com/10351221/121839846-931e4400-cca0-11eb-8712-76619c94fffb.png)
![2021-06-13_23 35 42](https://user-images.githubusercontent.com/10351221/121839847-93b6da80-cca0-11eb-868c-c51f1e0319a4.png)

My modpack version 

https://www.curseforge.com/minecraft/modpacks/fiction-friction/files/3351206 

Are you mutating graphics verts or lighting? I am really confused how your mod affects block models in any capacity.

**Comment by SuperMartijn642** [comment]
Tesseract uses the same code as the end portal.

![2021-06-14_11 23 42](https://user-images.githubusercontent.com/12382965/121870379-491a7a00-cd03-11eb-98e7-c5fc72abf18e.png)

I am unable to replicate this, are you sure it is caused by Tesseract?
Are there any steps I should take for it to happen?

**Comment by P3rf3ctXZer0** [comment]
Only certain angles

**Comment by P3rf3ctXZer0** [comment]
No its very hit and miss

**Comment by P3rf3ctXZer0** [comment]
If you ever wanted to jump on my server I can op you for testing purposes.

**Comment by P3rf3ctXZer0** [comment]
It does not happen unless you are on a dedicated server - forgot to mention.

**Comment by P3rf3ctXZer0** [comment]
I am getting ready for bed though ... so it may be later if you wanted to tell me your ingame name I can op you before I sleep.

**Comment by P3rf3ctXZer0** [comment]
https://youtu.be/f_qfEMK8w80 

Edit what I mean't to say was "Removing phosphor has no affect." also I hate outros XD

**Comment by SuperMartijn642** [comment]
It *should* be fixed now in version 1.0.22.

**Comment by P3rf3ctXZer0** [comment]
Thank you testing now.

**Comment by P3rf3ctXZer0** [comment]
It is fixed.

**Comment by SuperMartijn642** [comment]
Great, thank you for reporting the issue and helping me out!

**Comment by P3rf3ctXZer0** [comment]
Anytime.
