### ISSUE TITLE
[Bug] No Scrollbars in the channelwindow

### ISSUE THREAD

**Issue by skulldrago** [SuperMartijn642/Tesseract#29]
**Version Info**
- Minecraft, 1.12.2
- Tesseract, 1.0.21

**Description of the Bug**
I have a extreme reactor and want connect 32 turbines. For fluid Transfer i use tesseracts. So i need 2 channel for each turbine.
After 12 channel i can add channels but can´t see them and have no scrollbar apearing

**Steps to Reproduce**
add 12 channel in one section (item, energy or fluid)
add the 13 channel and you cant´t see him

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
I haven't added a visual scrollbar yet, but you can still just scroll up and down through the list.

**Comment by skulldrago** [comment]
How can i do this. The middle mouse button have no function there and the cursor-keys on my keyboard not, too.
Or is there any keybinding i can change in the options to scroll through the list?

**Comment by SuperMartijn642** [comment]
It might be that I have messed it up for 1.12 then. What I meant was just using the scrollwheel.
I don't have access to a computer now, so I will have to check after the weekend.

**Comment by skulldrago** [comment]
The scrollwheel have no function in the list for me. Your lib can not be the error? because i use the latest for 1.12.2 not the version which was from the mod asked for. If it can be a possible problem by the lib i can check this and tell you before the weekend is over.

**Comment by skulldrago** [comment]
Have found the reason for the bug?

**Comment by SuperMartijn642** [comment]
Turns out the mouse coordinates were being translated twice, thus the scroll area ended up over to the right and bottom of where it should be.
I fixed it now in the Core lib version 1.0.9a for Minecraft 1.12.

Thank you for reporting the issue!
