### ISSUE TITLE
Encountered an error

### ISSUE THREAD

**Issue by Baggytrousers27** [SuperMartijn642/Tesseract#30]
supermartijn642configlib-1.0.9-mc1.17
supermartijn642corelib-1.0.12-mc1.17
Tesseract-1.0.23-mc1.17
Forge 17.17.1-37.0.31(33)

Tesseract (tesseract) encountered an error during the common_setup event phase.

Tesseract (tesseract) encountered an error during the error event phase.

[Crashlog](https://pastebin.com/CZn7G7Zw)

**Comment by SuperMartijn642** [comment]
I fixed it now in Tesseract version 1.0.23a.

Thank you for reporting the issue!
