### ISSUE TITLE
[Bug] Losing Data

### ISSUE THREAD

**Issue by lvzxr** [SuperMartijn642/Tesseract#31]
**Version Info**
- Minecraft, 1.12.2 Forge 14.23.5.2855
- Tesseract, 1.0.22

**Description of the Bug**
After setting up all my tesseracts and running into no issues I had a power outtage causing my server to immediately close. When I got back onto the server I noticed that all the item, energy and some of the fluid channels that I had created had vanished

**Steps to Reproduce**
Instantly close server / Force power off comptuter

**Screenshots**
N/A

**Comment by SuperMartijn642** [comment]
There's nothing I can do about suddenly ending the server process. The tesseract channels are saved together with the world, so every time you pause the game in single player and every time the world is saved on a server.

Minecraft servers will already save the world periodically and when there are no players in a dimension. You can also manually run `/save-all` to make sure the world is saved.
