### ISSUE TITLE
[Bug] Redstone signal has no effect

### ISSUE THREAD

**Issue by Bollsjen** [SuperMartijn642/Tesseract#33]
No matter what setting I use in the tesseract GUI I can't turn the Tesseract on and off. Does not matter if I set the redstone signal setting to high or low and then send a redstone signal on high into the tesseract to turn it off. The tesseract will just not turn off on redstone signal. The version I use is 1.0.23-mc1.12.

Is this a bug or not just fully developed?

**Comment by SuperMartijn642** [comment]
It seems to work just fine on Minecraft 1.12 with Tesseract 1.0.23.
https://imgur.com/8mEibKA.gif

**Comment by Bollsjen** [comment]
> 
> 
> It seems to work just fine on Minecraft 1.12 with Tesseract 1.0.23.
> https://imgur.com/8mEibKA.gif

Interesting :/ When I do the same it still outputs power. The insides does disappear but it still ouputs power

**Comment by Danimation2001** [comment]
Hi,
I just want to add that this seems to also be an issue in version 1.0.23 - MC 1.16 too. Playing on FTB OceanBlock, setting the redstone control mode and then supplying a signal (I just used a lever) causes the block model to change to be just the tesseract frame (signalling off) but power is still drawn from the tesseract. I didn't test with items or fluids, just energy as that was what I was using it for.

**Comment by SuperMartijn642** [comment]
I fixed it now in Tesseract version 1.0.24.

Thank you both for reporting the issue!
