### ISSUE TITLE
[Bug] Dark and slightly flickering color inside Tesseract when using shaders

### ISSUE THREAD

**Issue by roroB20** [SuperMartijn642/Tesseract#34]
**Version Info**
- Minecraft 1.12.2
- Tesseract-1.0.24-mc1.12
- OptiFine_1.12.2_HD_U_G5
- ComplementaryShaders_v4.2.2

**Description of the Bug**
When shaders are turned on, the "ender portal effect" inside Tesseract become black and slightly flickers.
No light is emitted unlike the regular texture of the ender portal.

**Screenshots**
Regular ender portal using shaders:
![2021-11-12_02](https://user-images.githubusercontent.com/186746/141378399-d36a85fe-6f11-476e-a29b-604ab5d0945c.jpg)

Tesseract using shaders:
![2021-11-12_02 28](https://user-images.githubusercontent.com/186746/141378498-d90838b7-34bd-4bb5-a4a1-72507f6792c9.jpg)

**Comment by SuperMartijn642** [comment]
Nothing I can do about this sadly, I have no control over the shaders.
