### ISSUE TITLE
Minecraft 1.18.1 - ATM 7 0.2.34 - Server crash loop - logs suggest something to do with Pipez/Tesseract

### ISSUE THREAD

**Issue by D0ucheos** [SuperMartijn642/Tesseract#35]
Version: Minecraft 1.18.1
Modpack:  ATM 7 0.2.34

We were tidying up our base using pipez and the tesseract to move power and items about and it inexplicably started to crash.

It was working fine for 36 hours after we updated. Server was updated 21/01/22 10:00 AEST (GMT +10)

I have attached the first 4 crash files to the ticket, they repeat in size and included data, in a rolling loop. Current date and time 22/01/22 19:23 AEST (GMT +10)
[crash-2022-01-22_17.10.03-server.txt](https://github.com/SuperMartijn642/Tesseract/files/7918041/crash-2022-01-22_17.10.03-server.txt)
[crash-2022-01-22_17.10.57-server.txt](https://github.com/SuperMartijn642/Tesseract/files/7918042/crash-2022-01-22_17.10.57-server.txt)
[crash-2022-01-22_17.13.24-server.txt](https://github.com/SuperMartijn642/Tesseract/files/7918043/crash-2022-01-22_17.13.24-server.txt)
[crash-2022-01-22_17.07.37-server.txt](https://github.com/SuperMartijn642/Tesseract/files/7918044/crash-2022-01-22_17.07.37-server.txt)

**Comment by SuperMartijn642** [comment]
> It was working fine for 36 hours after we updated. Server was updated 21/01/22 10:00 AEST (GMT +10)

What did you update?

**Comment by Piratkopia13** [comment]
I had this crash today as well. This is a good repro for it https://github.com/henkelmax/pipez/issues/85
Not sure if the issue is with Tesseract or Pipez, but the crash is really bad and we had to open the world in an external program to remove the tesseracts before we could run the server again.

**Comment by SuperMartijn642** [comment]
I have added checks to prevent recursive calls to tesseracts, so it should fix this issue.
It is available as Tesseract 1.0.25.

Thank you both for reporting the issue!
