### ISSUE TITLE
[Question] ...Why do you say legal ownership of the tesseract is yours when it wasn't your idea?

### ISSUE THREAD

**Issue by hypernova132** [SuperMartijn642/Tesseract#36]
**Question**
...

And who gave you permission to re-create this feature?

**Comment by SuperMartijn642** [comment]
I assume you are referring to what is stated on the CurseForge page for Tesseract.
Which is:
> Tesseract is the property of SuperMartijn642 and is protected under copyright law and may not be altered or reuploaded without direct permission from SuperMartijn642.

Note that 'Tesseract' here is referring to this mod specifically, not to the concept of tesseracts. All of the code, textures, and models for Tesseract are created by me. Thus, they are '[my] property and protected under copyright law'.

The reason this is on the mod page for Tesseract (and my other mods) is not to discourage anyone from making a similar mod or taking inspiration from Tesseract, but rather to discourage mod rehosting sites such as _9minecraft_ from reuploading my mods.
