### ISSUE TITLE
[Bug] Tesseract not pulling energy from source

### ISSUE THREAD

**Issue by Blazeandcake** [SuperMartijn642/Tesseract#39]
**Version Info**
- Minecraft, 1.18
- Tesseract, All the mods 7 version

**Description of the Bug**
I use All the mods  7 on a small private server with friends. I made a nuclear reactor from the modpack "bigger reactors", and i want to use tesseract in order to get that energy to other places. I place the tesserect at the power output block from the reactor, and I place the other tesseract next to a charging station from "Charging gadgets". I correctly connect both tesseracts to the same network and correctly assign them the send and recieve labels. This is where my problem begins. The charging station won't get power through the tesseract. However, if I disconnect from the server and then reconnect, the charging station will suddenly have 1 million FE stored (it's maximum holding capacity). So basically, the charging station will only consistently get power through the tesseract if I disconnect and reconnect to the server.

**Steps to Reproduce**
It's explained above

**Screenshots**
![2022-04-13_00 43 56](https://user-images.githubusercontent.com/103527483/163066579-4b14c0ce-4499-4dd2-834b-de064916fb8d.png)

**Comment by SuperMartijn642** [comment]
This seems like an issue with Charging Gadgets as the charging station is not syncing its stored energy with the client.
Could you test if it works with another machine (from another mod) instead of the charging station?

**Comment by Blazeandcake** [comment]
It didnt look like a problem with the charging gadgets because I have used it like this on other types of machines from other modpacks. However, I have got a quick fix around this now. I have now connected the tesseract with the reactor through an energy pipe. It seems to need this pipe in order to pull from the reactor. 
Like so:
![2022-04-13_01 09 09](https://user-images.githubusercontent.com/103527483/163069144-4a8f21f3-d8ea-476b-bb82-756d3d9f52e0.png)

So with this current setup, it is working. But it does not make sense that I need the energy pipe, does it?

**Comment by SuperMartijn642** [comment]
Does it work correctly if you just put the charging station directly against the output of the generator? Thus without piped or tesseracts in between.

**Comment by CLASIX** [comment]
Hello. I am also having a similar issue. The tesseract sometimes pulls energy from source. sometimes it doesn't. I have to break the tesseract and reset the channel for it to start pulling power again. It stops intermittently and I cant quite figure out why. I have tried multiple different energy cables. This happens regardless of the cable or energy source. 
I have attached a short YouTube video showcasing the issue. 
https://youtu.be/1ZgJ4OW5ufM 

Tesseract 1.0.26
MC 1.18
Forge 40.1.47
DW 1.18 Pack

**Comment by TacoBoyy** [comment]
I'm also having the same problem as @CLASIX

**Comment by LuigiTP** [comment]
Same issue here and everyone is being affected it seems like it stops being loaded for some reason 
1.18.2
forge 40.1.47
Multiplayer server

**Comment by joshuadyson** [comment]
experiencing the exact same issue
DW 1.18 Pack
Multiplayer server
1.18.2

**Comment by SuperMartijn642** [comment]
Please create your own issue with more details. The only helpful comment for me is the one from @CLASIX, however that is also unrelated to the original issue reported by @Blazeandcake.

**Comment by SuperMartijn642** [comment]
@Blazeandcake the issue seems to be the reactor simply not pushing energy. You'll always need some pipe or machine to pull from it. In this case you can simply place one tesseract directly against the reactors power tab and use pipes to pull energy from the other tesseract.
