### ISSUE TITLE
[Request] More expensive recipe

### ISSUE THREAD

**Issue by AlienXtream** [SuperMartijn642/Tesseract#4]
i know that using mods like crafttweaker we can create recipes ourselves but it would be nice if a config option for using the "classic" TE recipe if its installed would be nice as many players who download this are probably going to want that and having packaged with the mod rather than relying on players creating custom recipes would be logical IMO.

**Comment by SuperMartijn642** [comment]
I definitely agree, that the classic recipe would be a nice addition.
The main problem is that many mods, including Thermal Expansion, aren't yet available for 1.14, 1.15 and 1.16. Items like enderium and pyrotheum dust, thus also aren't available.

**Comment by AlienXtream** [comment]
i did not realise this was available for those versions. i was in fact referring to the 1.12 version

**Comment by SuperMartijn642** [comment]
I might reconsider this as a config option once Thermal Foundation is released for 1.14, 1.15 and 1.16, as it should have all the required items.
For now, I won't be adding it, as it would only be possible for 1.12.
