### ISSUE TITLE
[Bug] [1.12.2] tesseract clearing channels

### ISSUE THREAD

**Issue by sofiaeris** [SuperMartijn642/Tesseract#40]
**Version Info**
- Minecraft, 1.12.2
- Tesseract, tesseract-1.0.25-mc1.12.jar

**Description of the Bug**
when the server restarts, non-chunkloaded tesseracts seem to clear channels and have to be reconfigured

**Steps to Reproduce**
place tesseract in chunks, unload them, restart server

**Comment by SuperMartijn642** [comment]
Thank you for reporting the issue!

Although I haven't addressed (or replicated) this issue specifically, the underlying code has changed significantly since this issue was created and I believe it is no longer relevant.
