### ISSUE TITLE
[Crash] Unknown crash with Mekanism

### ISSUE THREAD

**Issue by TheFantasticLoki** [SuperMartijn642/Tesseract#42]
**Version Info**
- Minecraft, 1.18.2 Forge 4.1.19
- Tesseract, 1.0.26

**Steps to Reproduce**
Unknown

**Crash report (~/logs/latest.log)**
[crash-2022-05-21_12.50.52-server.txt](https://github.com/SuperMartijn642/Tesseract/files/8747741/crash-2022-05-21_12.50.52-server.txt)

Woke up to this on the server this morning.

**Comment by Raidobw2** [comment]
There is a similar case of this at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1186 with `tesseract-1.0.27`, though it manipulates Forge Energy while here the crash is mentioning fluids. Both interactions are with Mekanism cables though. There's more different crashes on that linked issue too.

Is there something I could do to help for that error? Such as reproduce it or ask the user on the linked issue to try test builds?

**Comment by SuperMartijn642** [comment]
Whoops sorry Raidobw2, I completely missed you're reply. Even though I don't know the exact cause of the issue, I do have some changes in mind which may help.
I am currently quite busy with some other stuff which I want to finish first, so it might be a bit before I can do another pass over Tesseract.

**Comment by Raidobw2** [comment]
No problem, thank you for informing me. Once you get back into Tesseract at some point, feel free to ping me if you need some help testing things or reproducing it, I'll be glad to help :^)

**Comment by SuperMartijn642** [comment]
Thank you for reporting the issue!
I have made significant performance improvements and I have added checks to prevent infinite loops, so this issue should be fixed now.
