### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by Gabius678** [SuperMartijn642/Tesseract#43]
**Version Info**
- Minecraft, FTB 10th anniversary 1.3.0
- Tesseract, 1.0.24

**Description of the Bug**
unable to use ftb industrial contraption for energy output (input works)

**Steps to Reproduce**
send energy with ftb industrial contraption into tesseract and output with cable.

**Comment by SuperMartijn642** [comment]
What Minecraft version are you using?

**Comment by Gabius678** [comment]
Yeah sorry forgot to write it, it’s the 1.16.5 one 
Btw thanks for your work I really like tesseract

**Comment by github-fave** [comment]
+1 for issue with the same steps

**Comment by SuperMartijn642** [comment]
Industrial Contraptions uses its own type of energy instead of the energy system provided by Forge, i.e. Forge Energy (FE). Tesseract only works with FE.
