### ISSUE TITLE
[Bug] Fluid Piping Redstone breaking Tesseract functionality

### ISSUE THREAD

**Issue by 595dylan** [SuperMartijn642/Tesseract#45]
FTB Direwolf20 1.18 Modpack latest version 1.4.1
**Version Info**
- Minecraft, 1.18
- Tesseract, 1.0.26-forge-mc1.18

**Description of the Bug**
Definitely: Fluid piping for Mekanism and possibly other fluids breaks while using any of the Redstone control functions (ie. High, Low, and Disabled). In one example, I had one tesseract disabled from the channel and it still piped fluid regardless. The bug seems to be complicated and I couldn't fully pin down the exact issue(s).

**Steps to Reproduce**
Simply connect to tesseracts via a fluid channel and attempt to control the flow of fluid via the tesseracts Redstone settings.

**Screenshots**
This is a test system where I made the left Mekanism pipe pull from the tank and, despite the other Tesseract being disabled with the redstone settings, it still transported the fluid.
![image](https://user-images.githubusercontent.com/107741179/174423262-32beccba-9aff-476f-9aac-7605623d3b0c.png)
Left Tesseract GUI:
![image](https://user-images.githubusercontent.com/107741179/174423271-c13e4a0e-98c2-4de7-96fe-5bb41fc350ca.png)
Right Tesseract GUI:
![image](https://user-images.githubusercontent.com/107741179/174423275-d1f7a415-9f00-4003-9b74-1909fffff6c8.png)

It generally appears that any of the Redstone settings mess any system up.

**Comment by SuperMartijn642** [comment]
Thank you for reporting the issue!

This should hopefully be addressed now in Tesseract version 1.0.30. Anyways, the underlying code has changed quite a bit since this issue was created, please create a new issue if the problem persists.
