### ISSUE TITLE
Tesseracts Stop Functioning

### ISSUE THREAD

**Issue by tmanfoo1** [SuperMartijn642/Tesseract#49]
**Version Info**
- Minecraft,1.18.2
- Tesseract,
tesseract-1.0.27-forge-mc1.18.jar

**Description of the Bug**
Tesseracts seem to randomly stop working, then need to be broken and replaced to begin functionality

**Steps to Reproduce**
The steps to reproduce are not exactly clear, but it seems that tesseracts are just randomly deciding to not function, especially if multiple on the same channel are put in the same area 
**Screenshots**
I will try to provide some when I see them again 
[On average they happen 5/32 times on a daily basis]

**Comment by tmanfoo1** [comment]
Additionally, We are using it on servers, so I am not sure if that contributes.

**Comment by Septem151** [comment]
I'm also experiencing this same issue on 1.18.2, tesseract-1.0.27-forge-mc1.18.jar
Usually occurs after I log out of the world and relog in. This occurs on every single player world I've created, whether it be survival or creative. RF will drip through at a rate of about 0.1 RF/t until all Tesseracts are broken and replaced.

**Comment by SuperMartijn642** [comment]
Thank you for reporting the issue!

I have made some significant changes now in Tesseract version 1.0.30 which should hopefully address this issue. If the problem persists, please create a new issue.
