### ISSUE TITLE
[1.12] When log out the world the tesseract will unselected channel.

### ISSUE THREAD

**Issue by ZHENGLOC** [SuperMartijn642/Tesseract#5]
Sorry my english is poor.

mod version: tesseract-1.0.7-mc1.12
forge version: 14.23.5.2854

https://i.imgur.com/axt4vhR.gif

**Comment by SuperMartijn642** [comment]
Does this happen with every tesseract or just the one you placed there?
In which dimension did this happen?

**Comment by SuperMartijn642** [comment]
Same as mentioned in #8.

It is fixed now in verison 1.0.8, thanks for the report!
