### ISSUE TITLE
Causing long Tick times when multiple tesseracts are in unloaded chunks

### ISSUE THREAD

**Issue by Petrify** [SuperMartijn642/Tesseract#50]
### Issue:
Tesseracts were causing ticks to take long (2500+ ms) whenever an AE2 export bus tried to push items into the Tesseract. The Behavior can be replicated by using a hopper, so it's not AE2 specific. The Issue arose after building something that had 1 input tesseract and a total of 56 output tesseracts most of which were in different chunks from each other. In my case a distribution system for ammunition for turrets (See images below). I ran the Spark profiler on my server and traced it back to Tesseracts. You can view the Profiler's report [here](https://spark.lucko.me/mmQMLoRka5) or alternatively upload the file contained in [this archive](https://github.com/SuperMartijn642/Tesseract/files/9494304/sparkprofile.zip) to [this website](https://spark.lucko.me/)

From the Profiler's Stacktrace it seems that the call to `com.supermartijn642.tesseract.manager.TesseractReference.isValid()`  loads the chunks of tesseracts that are unloaded, causing lots of chunks to be checked in a single tick. When the server restarts and forcefully unloads all these chunks, the tesseracts become unloaded and the issue begins.

### Further notes:
 - Minecraft Version: 1.18
 - Mod Version: 1.0.27
 - Forge Version: 40.1.69 
 - Modpack: Direwolf20 1.18
 - All the target inventories are completely filled.
 - Only tested with Pneumaticraft turrets as targets.

### Images:
![2022-09-06_03 14 57](https://user-images.githubusercontent.com/13384711/188571430-8a01218f-ac79-4983-8bac-fc28ff658c59.png) Sender Tesseract. Removing the Export Bus fixes the issue. 

![2022-09-06_03 31 56](https://user-images.githubusercontent.com/13384711/188575486-100ca4ef-88f5-4420-8114-e46c494304c1.png)
Receiver Tesseracts. One beneath each turret

Hope this Report is thorough enough! If you require any more information shoot me a message

**Comment by SuperMartijn642** [comment]
Thank you for reporting the issue!

I have made some significant performance improvements now in Tesseract version 1.0.30, so performance issues like this should now be fixed.
