### ISSUE TITLE
Question: Behavior of multiple Tesseracts receiving one Channel

### ISSUE THREAD

**Issue by DrowningDevil** [SuperMartijn642/Tesseract#51]
Hello!

I have a question on the behavior of item transfer:
If I have multiple Tesseract and set them all to receive the same channel - how is it determined to which Tesseract the item transfers?

Thank you!
-Devil

**Comment by SuperMartijn642** [comment]
All tesseracts are stored in internal lists, so the first tesseract in that list will get the item, then the second, and so forth. The order of this list is pretty much random.
