### ISSUE TITLE
Doesn't work with mekanism logistical transporters

### ISSUE THREAD

**Issue by Sovietsupporter69** [SuperMartijn642/Tesseract#52]
Just as the title says mekanism's logistical transporters aren't extracting or inserting items, they are connecting but nothing is happening. I have tested this with xnet as a replacement and it works perfectly fine so I'm sure mekanism's at fault. Might matter that I have only tested this with the advanced transporters but I don't see there being any difference.

I'm running 1.0.27 for 1.18 forge and am on a single player world, should be reproducible if you look at the images below. Also could someone tag this as a bug I don't know how to.
![2022-09-19_23 10 10](https://user-images.githubusercontent.com/84580170/191128610-c86f29dd-c865-4ea4-a2f2-b6593c3274ab.png)
![2022-09-19_23 10 15](https://user-images.githubusercontent.com/84580170/191128613-b2e1bfe3-d1f0-45f5-bdc1-12e6b8af1ded.png)
![2022-09-19_23 05 25](https://user-images.githubusercontent.com/84580170/191128322-af588c43-e00f-406b-853f-49462d8a7ff8.png)
![2022-09-19_23 05 28](https://user-images.githubusercontent.com/84580170/191128332-bc95f58c-5ecf-49d5-a8e3-f6af1384b3d2.png)

**Comment by SuperMartijn642** [comment]
When a pipe tries to insert to/extract from a tesseract, the tesseract will look for inventories around other tesseracts on the same channel. Most pipes don't actually have inventories, thus the tesseract doesn't find anything. Your issue can be resolved by placing one of the chests directly against the tesseract and leaving a pipe connected at the other tesseract.

**Comment by Sovietsupporter69** [comment]
Thanks for the response as I can now fix this but this should still be a thing you can do.
