### ISSUE TITLE
[Bug] Tesseracts losing power transmitting functionality after world reload

### ISSUE THREAD

**Issue by Bowzerz9001** [SuperMartijn642/Tesseract#56]
1.18.2
tesseract-1.0.27-forge-mc1.18

Everytime I'd load up my world after not playing for a little while my tesseracts would stop transmitting power but not fluids or items

**Comment by SuperMartijn642** [comment]
Please explain the steps to reproduce the issue.

**Comment by Bowzerz9001** [comment]
Ok so it turns out, that it saw the one motor from the Create Additions mod that I was running it to through Mekanism cables as nothing and wasn't sending power to it

**Comment by Bowzerz9001** [comment]
I originally had it right next to it and it worked fine until a reload
Then I had it hooked up to Mekanism cables and it also worked fine until a reload

**Comment by SuperMartijn642** [comment]
Should be fixed now in Tesseract 1.0.30.
Thank you for reporting the issue!
