### ISSUE TITLE
[Bug] Issues With Transporting Multiple Types

### ISSUE THREAD

**Issue by Parker-Bergen** [SuperMartijn642/Tesseract#57]
**Version Info**
- Minecraft, 1.18 - FTB Stone Block 3 Version: 1.0.2
- Tesseract, 1.0.27

**Description of the Bug**
When setting up tesseracts that transport multiple types, their is an issue with those types being input and output.
Example: Tesseract will transfer power, but will not transfer items.
There have been many bug reports over the pipes not allowing items to input and export out of the tesseract, and the solution was to put a block next to the tesseract, I have found that this was not acting as intended unless I broke and replaced the tesseract.

**Steps to Reproduce**

Place down 2 tesseracts.
Put a chest next to 1 tesseract
Place a pipe and a chest into the other.
Create an item channel and select for both. Pipe as send and chest as receive
This works to transfer items

-----

Now place a empty energy cell on tesseract with the pipe.
Place an full energy cell on the chest tesseract.
Make energy channel and set empty cell side as receive and full cell as send and recieve
The energy will not flow through the tesseract to the other tesseract.
This is the problem...

----

The solution:
If you break both tesseracts and replace them with all the input and output blocks surrounding, and set the channels correctly, then the energy and items will flow through

**Comment by SuperMartijn642** [comment]
Jankiness like this should hopefully be fixed now in version 1.0.30.

Thank you for reporting the issue and the great instructions!
