### ISSUE TITLE
[Feature] Channel remove confirmation

### ISSUE THREAD

**Issue by TheLetslook** [SuperMartijn642/Tesseract#60]
**Is your feature request related to a problem? Please describe.**
I accidentally deleted my channels a couple of times, it caused me some problems in the automation circuits.

**Describe the solution you'd like**
I suggest adding a confirmation window, when you try to delete a channel, it will open and you will need to confirm or reject the deletion.

**Comment by SuperMartijn642** [comment]
Very good suggestion. I wonder why I didn't just do this to begin with, just one click to delete an entire channel seems a bit insane.

**Comment by SuperMartijn642** [comment]
I added the confirmation screen now in version 1.0.30.

Thank you for the suggestion!
