### ISSUE TITLE
[Bug] LaserIo seem to not interface with Tesseract

### ISSUE THREAD

**Issue by Pultex** [SuperMartijn642/Tesseract#62]
**Version Info**
- Minecraft, 1.18.2
- Tesseract, tesseract-1.0.27
- laserio-1.4.5
- 1.18.2-forge-40.1.84

**Description of the Bug**
LaserIO tries to send fluid into Tesseract nothing gets sent
Fluid is life essence from Blood magic

**Steps to Reproduce**
place laserio next to altar with tesseract next to laserio
set tesseract with channel for fluid and link the other tesseract
place second laserio next to tank and tesseract
see nothing transfers

[fluid cards are in laserio did not think you needed info for how laserio works]

**other info**
ended up just linking multiple LaserIOs in chain to get same result
was only 12 blocks away in next chunk to the north

**Comment by SuperMartijn642** [comment]
Place the tesseract directly against the tank.
The tesseract itself doesn't store any liquid, instead the blocks insert directly into the blocks next to the tesseract. So right now you'd have laserio inserting into laserio, which I assume doesn't work.
