### ISSUE TITLE
Tesseract not transferring items?

### ISSUE THREAD

**Issue by SuperMonkey1308** [SuperMartijn642/Tesseract#64]
I am playing on a server with tesseract and Ender IO, and I'm trying to send items through the tesseract but no items are going through. The attached images show the setup that I have with my tesseracts (honestly I'm trying everything and nothing is working)

![image](https://user-images.githubusercontent.com/124469263/216790505-08bb3c13-5d0a-493f-97f2-6f8531a0b8c7.png)
![image](https://user-images.githubusercontent.com/124469263/216790518-1c4f61d4-cdb6-4399-9798-d7bf75e4c754.png)
![image](https://user-images.githubusercontent.com/124469263/216790523-954d9eb4-20d4-4edf-8645-0a3d20c6e01b.png)
![image](https://user-images.githubusercontent.com/124469263/216790529-f20399a5-5c30-42c0-b54a-6da02a5b4d6d.png)

(also yes, I made sure to set the extraction to "always active")

**Comment by SuperMartijn642** [comment]
Please fill in the template next time. What version of Minecraft and Tesseract are you using?

From what I can see, only in the second screenshot an item conduit is connected to the tesseract. Both on the chest and the tesseract, the conduit is set to insert, could that be the issue?

**Comment by SuperMartijn642** [comment]
Closing this as I don't know which version of Minecraft and Tesseract are even being used.
