### ISSUE TITLE
[Crash] issue - serv laging

### ISSUE THREAD

**Issue by egorste** [SuperMartijn642/Tesseract#65]
**Version Info**
- Minecraft, 1.19.2
- Tesseract, 1.0.29-forge-mc1.19

**Steps to Reproduce**
i don't know why the serv is laging but when someone connect to it, it seems that the avg response time is growing, and then the serv crash...

**Crash report (~/logs/latest.log)**
https://spark.lucko.me/XUbNjqp2hv

**Comment by SuperMartijn642** [comment]
Thank you for reporting the issue!

Tesseract version 1.0.30 now includes some significant performance improvement, so should be fixed now.
