### ISSUE TITLE
[Crash] ... Installed Tesseract 1.0.29 for MC 1.12.2 on DW20 1.12.2 and crash!

### ISSUE THREAD

**Issue by llloyd4** [SuperMartijn642/Tesseract#66]
**Version Info**
- Minecraft, ... 1.12.2
- Tesseract, ... 1.0.29

**Steps to Reproduce**

Install tesseract-1.0.29-forge-mc1.12 & supermartijn642configlib-1.1.6-forge-mc1.12 & supermartijn642corelib-1.1.7-forge-mc1.12 into the /mods folder for DW20 1.12.2 v2.9.0 mod pack and try to start that Instance / Modpack

**Crash report (~/logs/latest.log)**

[crash-2023-04-14_05.14.29-client.txt](https://github.com/SuperMartijn642/Tesseract/files/11232757/crash-2023-04-14_05.14.29-client.txt)
[2023-04-14-4.log](https://github.com/SuperMartijn642/Tesseract/files/11232786/2023-04-14-4.log)

**Comment by SuperMartijn642** [comment]
Appears to be caused by Phosphor. Phosphor for Forge has been unsupported for years now and its source code is no longer available, so there's nothing I can do about it.

If it is not Phosphor, please narrow down the other mods needed to reproduce the issue and let me know.

**Comment by llloyd4** [comment]
> Appears to be caused by Phosphor. Phosphor for Forge has been unsupported for years now and its source code is no longer available, so there's nothing I can do about it.
> 
> If it is not Phosphor, please narrow down the other mods needed to reproduce the issue and let me know.

Bingo! I removed Phosphore and Dynamic Lighting (since I have Optifine installed that does that anyway. >.< ) and it loads up just fine. Thank you. Now, let's test the limits of the Tesseract. :D (two 32k rf/t solars that'll soon feed a DE energy sphere. :D )
