### ISSUE TITLE
[Bug] No ui un tesseract

### ISSUE THREAD

**Issue by bagou4502** [SuperMartijn642/Tesseract#67]
**Version Info**
- Minecraft, 1.19.4
- Tesseract, 1.0.29-forge

**Description of the Bug**
The ui of the tesseract is empty

**Steps to Reproduce**
Install the mod on 1.19.4. Open the tesseract interface

**Screenshots**

![image](https://user-images.githubusercontent.com/53863206/232329978-30d20aec-8b12-49b8-a6fd-cdca6da08138.png)

And after that chest,player,item ect are just invisible
https://cdn.bagou450.com/sdsfFDSQEFZDSdf456sdfCVDS165vsdfesvesv.mp4

**Comment by bagou4502** [comment]
And after that chest,player,item ect are just invisible

**Comment by SuperMartijn642** [comment]
Should be fixed now with dedicated file for 1.19.4.
Thank you for reporting the issue!

**Comment by bagou4502** [comment]
Thanks ! that work fine
