### ISSUE TITLE
[Crash] [1.16.5] Crash on startup

### ISSUE THREAD

**Issue by aking4125** [SuperMartijn642/Tesseract#68]
Hello,

Upon loading the mod pack, the game crashes with the following error log below:

[debug.log](https://github.com/SuperMartijn642/Tesseract/files/11257945/debug.log)

Removing this mod allows the game to start normally.

Any Ideas?

**Comment by SuperMartijn642** [comment]
Please fill in the information in the template next time.

You are using a lot of mods and the error message is cut off. Could you narrow down the mods needed to reproduce the issue?

**Comment by aking4125** [comment]
[crash-2023-04-18_09.31.16-fml.txt](https://github.com/SuperMartijn642/Tesseract/files/11262279/crash-2023-04-18_09.31.16-fml.txt)

Same error as above but with just:

tesseract-1.0.30-forge-mc1.16.jar
supermartijn642corelib-1.1.7-forge-mc1.16.jar
supermartijn642configlib-1.1.6-forge-mc1.16.jar
forge-1.16.5-36.2.39

**Comment by SuperMartijn642** [comment]
Thanks @aking4125, that one does show the full error. I will push an update once I am home.

**Comment by SuperMartijn642** [comment]
It is fixed now in version 1.0.30a for Minecraft 1.14, 1.15, and 1.16.

Thank you for reporting the issue!
