### ISSUE TITLE
[Crash] Extra Utilities Incompatibility.

### ISSUE THREAD

**Issue by Handeril** [SuperMartijn642/Tesseract#69]
**Version Info**
- Minecraft - 1.12.2, Forge Version 14.23.5.2860
- Tesseract - tesseract-1.0.32-forge-mc1.12.jar
- SuperMartijn642's Config Lib - supermartijn642configlib-1.1.6-forge-mc1.12.jar
- SuperMartijn642's Core Lib - supermartijn642corelib-1.1.7-forge-mc1.12.jar

**Steps to Reproduce**
This appears to involve Extra Utilities 2 Mechanical Users, and Tesseract itself or one of it's libraries.
The "Ticking Entities" in question are Mechanical Users set to infinitely-mine cobblestone using Unbreakable TConstruct Pickaxes.

- To reproduce the error, install Extra Utilities 2 and TConstruct (Latest Versions) with Tesseract.
- Place a mechanical user, set it to "Use Item on Block" (or Activate Block with Item), set it to Left-Click mode, and then set it to "Upper Left Slot Only".
- If the game hasn't died yet, put a TConstruct pickaxe in the upper left slot.
- If it still hasn't died yet, build a cobblestone generator in front of it.

- If all else fails with reproducing the bug, try disabling Tesseract (and it's libraries), starting a fresh world, building the contraption listed above, and then try re-enabling Tesseract.

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/Tesseract/files/1
[crash-2023-04-21_00.49.24-server.txt](https://github.com/SuperMartijn642/Tesseract/files/11293588/crash-2023-04-21_00.49.24-server.txt)
1293584/latest.log)

**Comment by SuperMartijn642** [comment]
The crash is caused by Tinkers Reforged and is unrelated to Tesseract. Please report the issue to them.
