### ISSUE TITLE
[Bug] Pipes don't work with tesseracts

### ISSUE THREAD

**Issue by bagou4502** [SuperMartijn642/Tesseract#70]
**Version Info**
- Minecraft, 1.19.4
- Tesseract, 1.0.32

**Description of the Bug**
The one prob show me in all case that the items channel is inactive. And i can't transfert item with pipe from pipez mod

**Steps to Reproduce**
Install the mod and pipez mods on 1.19.4

Try to transfert item
**Screenshots**
![image](https://user-images.githubusercontent.com/53863206/233610430-766c8e7f-9aeb-44e7-9a24-c4739d51a21c.png)
![image](https://user-images.githubusercontent.com/53863206/233610460-028f9e25-a353-4d16-bdd1-8061255ba23a.png)
![image](https://user-images.githubusercontent.com/53863206/233610503-52214a74-709e-4935-9d6f-6213278513cb.png)

**Comment by SuperMartijn642** [comment]
The tesseracts themselves don't store any items, so in this case one pipe is trying to push an item into another which does not work. Just place one of the tesseracts directly against the chest.

**Comment by bagou4502** [comment]
I got a chest connected to a pipe that push item in the tesseract. And the other tesseract where a pipe is connected and push item in a chest that work normally no?

**Comment by SuperMartijn642** [comment]
> Just place one of the tesseracts directly against the chest.

**Comment by Th3Fanbus** [comment]
A picture is worth a thousand words:

![2023-04-27_17 18 21](https://user-images.githubusercontent.com/22937129/234908503-ce44f4c2-fba1-4195-84ea-13ae12b56206.png)

This is on 1.19.2 but the same setup should work on any other version.

**Comment by SuperMartijn642** [comment]
Yup, thanks @Th3Fanbus. That makes it much clearer what I meant. Couldn't be bothered to start the game and make a screenshot 😅
Additional note, the same should work if you instead place the input against the chest and use a pipe at the output. It works the same way for fluids.
