### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by llloyd4** [SuperMartijn642/Tesseract#72]
**Version Info**
- Minecraft, ...1.12.2
- Tesseract, ... tesseract-1.0.29-forge-mc1.12

**Description of the Bug**
...
Doesn't transfer energy 

**Steps to Reproduce**
...
Drop some Solar Flux Reborn panels into the Aroma1997 mining dimension, drop a tesseract, create Energy network "Solar Panel lnetwork", activate it (so it has a check mark),  use either Thermal Expansion Fluxducts *or* Draconic Evolution Wyvern I/O Energy Crystals to connect solar panels to tesseract, back in overworld, drop tesseract, activate the "Solar Panel network" and use either TE Fluxducts or DE Wyvern I/O Energy Crystals to connect it to the input side of a DE Energy Sphere. 

**Screenshots**
...You sure about that? Ok. Incoming.

![2023-04-22_07 31 18](https://user-images.githubusercontent.com/7238110/233792654-e76a5318-c6b8-46b1-8b31-5cfb7316a83a.png)

![2023-04-22_07 31 09](https://user-images.githubusercontent.com/7238110/233792668-af7db704-cd96-4bdc-8448-fbc603b0d46f.png)

![2023-04-22_07 31 01](https://user-images.githubusercontent.com/7238110/233792687-cb1cc3f5-036b-4217-a440-4ec79f8832ed.png)

![2023-04-22_07 30 16](https://user-images.githubusercontent.com/7238110/233792708-0e9656d8-bfe9-410f-9351-908d5d5d45aa.png)

![2023-04-22_07 30 03](https://user-images.githubusercontent.com/7238110/233792726-7a03c3f3-6461-4453-8a15-091736d2e5d0.png)

![2023-04-22_07 29 55](https://user-images.githubusercontent.com/7238110/233792742-268c6401-dd85-4a1d-9c2d-c9e50a7c3add.png)

Don't have pictures of the Fluxduct network, but imagine a whole bunch of Cryo Stabilized Fluxducts running along the bottom of the solars to the top of the tesseract on the mining world side, and on the overworld side, from the top of the tesseract up to the input pylon of the DE Energy Storage Sphere. How I *finally* determined it was the tesseracts is that I took them out and put in a Flux Plug (on the solar side) and Flux Point on the overworld side (From the Flux Networks mod) and it started to work, all I changed was the tesseract. Went from -400 RF/T on the DE Energy Sphere to +400k RF/t, crisis averted. ><

**Comment by SuperMartijn642** [comment]
The tesseracts themselves don't store any energy. That means when the energy crystal in picture 2, tries to push energy to the tesseract, it wants to push energy to blocks around the tesseract in picture 5. However, most pipes (or in this case energy crystals) don't allow other things to push energy to them, rather they just pull energy themselves.

In case this the solution would to place the receiving tesseract directly against the energy acceptor for the energy sphere **or** place the sending tesseract directly against the solar panels.

(I am not 100% sure about the energy crystals as I haven't used the before. Might also just be fixed in newer versions of Tesseract.)

**Comment by llloyd4** [comment]
> The tesseracts themselves don't store any energy. That means when the energy crystal in picture 2, tries to push energy to the tesseract, it wants to push energy to blocks around the tesseract in picture 5. However, most pipes (or in this case energy crystals) don't allow other things to push energy to them, rather they just pull energy themselves.
> 
> In case this the solution would to place the receiving tesseract directly against the energy acceptor for the energy sphere **or** place the sending tesseract directly against the solar panels.
> 
> (I am not 100% sure about the energy crystals as I haven't used the before. Might also just be fixed in newer versions of Tesseract.)

Except I tried using cryo-stablized fluxducts too to 'wire' the tesseracts directly to both with the same results, I just didn't photo that.

**Comment by SuperMartijn642** [comment]
> Except I tried using cryo-stablized fluxducts too to 'wire' the tesseracts directly to both with the same results, I just didn't photo that.

That is exactly what I explained. You **cannot** push energy to or pull energy from a wire block. Just place the tesseract directly against the thing you're trying to pull from or push to.

**Comment by llloyd4** [comment]
That would mean something like a half a dozen or so tesseracts, one per solar panel. O.o

**Comment by SuperMartijn642** [comment]
That's why I suggested placing the tesseract directly against the input for the energy sphere. All you would need to change is placing the tesseract in picture 5 against the input block in picture 6 🙂

**Comment by llloyd4** [comment]
> That's why I suggested placing the tesseract directly against the input for the energy sphere. All you would need to change is placing the tesseract in picture 5 against the input block in picture 6 🙂

That still leaves the half a dozen or so solar panels, each generating 65k RF/t . Or, just a suggestion, doubt it'll be implemented, but probably round filed, you could add some storage to the tesseract, like it was another piece of 'wire' , like a flux duct, energy conduit, energy pipez, etc? As I said, it's just a suggestion but I fully expect you to reject it so... >.< I'll need to see if I can find a battery box that can output DE scale power and wire the panels into that then put a tesseract against that. * hmm *
