### ISSUE TITLE
[Crash] crash server

### ISSUE THREAD

**Issue by bigenergy** [SuperMartijn642/Tesseract#73]
**Version Info**
- Minecraft 1.19.2
- Tesseract, [tesseract-1.0.32-forge-mc1.19](https://mediafilez.forgecdn.net/files/4499/783/tesseract-1.0.32-forge-mc1.19.jar)

**Crash report (~/logs/latest.log)**
https://gist.github.com/bigenergy/1d73867c1e6a1a675e1a7aab2eb67ca8

**Comment by SuperMartijn642** [comment]
Fixed now in Tesseract 1.0.33.
Thank you for reporting the issue!
