### ISSUE TITLE
[Question] 1.19 fabric support

### ISSUE THREAD

**Issue by wackoamd1** [SuperMartijn642/Tesseract#74]
**Question**
...
like title says , can we get a 1.19 version for fabric?

**Comment by SuperMartijn642** [comment]
There already is

**Comment by wackoamd1** [comment]
uhm no there is not , 
1.19.4 for fabric  but that does NOT work on 1.19 , there is a forge version for 1.19 but not fabric.
hence my question

**Comment by SuperMartijn642** [comment]
Why would anyone play on 1.19? Just update to 1.19.4 or at least 1.19.2

**Comment by wackoamd1** [comment]
because the mods on the server are not all updated to that versions XD
