### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by EJTP** [SuperMartijn642/Tesseract#76]
Dear SuperMartijn642,

I hope this message finds you well. I am writing to request a feature for your mod, Tesseract, which I would love to see included in the upcoming 1.19.2 release. I plan to use your mod in my modpack and this feature would greatly enhance the overall gameplay experience.

My feature request is for the ability to customize the appearance of the Tesseract blocks. Specifically, I would like to be able to change the color and texture of the blocks to better match the aesthetic of my modpack. This would allow me to seamlessly integrate Tesseract into my pack without any jarring visual inconsistencies.

I understand that implementing such a feature may require some significant development effort, but I believe it would greatly enhance the versatility and appeal of your mod. Additionally, it would make it more appealing to modpack creators like myself who are looking for ways to personalize our packs.

Thank you for considering my feature request. I look forward to seeing Tesseract continue to evolve and improve with each new release.

**Comment by SuperMartijn642** [comment]
Wut? You can change the look of tesseracts with a resource pack just like any other block.

Also, what do you mean by 'upcoming 1.19.2 release'? It is already available for 1.19.2 on Forge and it won't be released for 1.19.2 on Fabric as it is already available for 1.19.4.
