### ISSUE TITLE
[Bug] Multiple Tesseracts cannot work on the same pipe

### ISSUE THREAD

**Issue by mingriyuan** [SuperMartijn642/Tesseract#78]
**Version Info**
- Minecraft, 1.12.2-Forge_14.23.5.2860
- Tesseract, tesseract-1.0.34-forge-mc1.12

**Description of the Bug**
Because Tesseract transmission is slow, I tried using four Tesseract and Thermal Dynamics pipes to set up 2 or 1 frequency band to speed up transmission. I found that no matter how many inputs or outputs were on the same pipe (and of course the inputs and outputs were isolated), only one Tesseract was working even when multiple bands were created. Found only when transporting items, no mixed fluid, energy.
Please try to solve it, thank you.

**Steps to Reproduce**
One side uses the Thermal Dynamics pipe to connect multiple Tesseracts as input (input-only), the other side uses the Thermal Dynamics pipe to connect multiple Tesseracts as output(output-only), you can set different frequency bands.

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Wut, tesseracts don't have any sort of limit on transfer rate. The things inserting into the tesseract are directly transferring to blocks around other tesseracts on the same channel.
