### ISSUE TITLE
[Bug] Tesseract sometimes loses channel

### ISSUE THREAD

**Issue by ThePixelbrain** [SuperMartijn642/Tesseract#79]
**Version Info**
- Minecraft, 1.12.2
- Tesseract, 1.0.34

**Description of the Bug**
Sometimes the Tesseract resets itself and loses its channel, stopping all energy transfer. I haven't been able to understand when or why it happens, since it only happens occasionally. I experienced it with two tesseracts. One is connected to a Leadstone Fluxduct and a Industrial Foregoing machine. The other one is just connected to Leadstone Fluxducts, which connect to a Industrial Foregoing machine.
It seems to be only happening after world or chunk loads. (The chunks are permanently loaded chunks in the overworld)

**Steps to Reproduce**
1. Place down Tesseract
2. Configure frequency and set to receive only
3. Connect Leadstone Fluxducts
4. Connect a Industrial Foregoing machine (tested with Bioreactor and Mob Duplicator)

**Screenshots**
![2023-05-16_18 22 31](https://github.com/SuperMartijn642/Tesseract/assets/19214217/d09c3562-5280-4099-8109-c428adf099b7)

**Additional notes**
The logs didn't show anything relevant. I'm uncertain if this has anything to do with Industrial Foregoing machines, but I experienced the issue with them. This could be a coincidence.

**Comment by OHOgameplay** [comment]
Same happens on 1.19.2. happens with energy, and liquid. It seems to be totally random, no matter of what mod the block that's connected to the thesseract belongs to.

**Comment by SuperMartijn642** [comment]
I fixed a bug now in version 1.0.36 where the data of the last placed tesseract in a save could be overwritten when a new tesseract is placed after loading a save. This would only become visible after then, again, saving and reopening the save.
I assume this is what you were experiencing, if you still encounter the issue with the updated version, let me know of course.
Thank you for reporting the issue!
