### ISSUE TITLE
[Question] What license is this under?

### ISSUE THREAD

**Issue by Cyanide-1** [SuperMartijn642/Tesseract#83]
**Question**

As the title says, i am asking which software license is this software under? is it under an open source software license?

**Comment by SuperMartijn642** [comment]
No license as I don't want to give away any rights which I may regret later. If you just want to use parts of the code and it's not like half the mod, I generally don't mind though.

Anyways, if you have something specific in mind and are unsure, feel free to just ask me 🙂
