### ISSUE TITLE
How do Channel connection work?

### ISSUE THREAD

**Issue by chokoth** [SuperMartijn642/Tesseract#86]
I am working on MC 1.20.1, on tesseract version 1.0.35a on fabric.

I have 4 tesseracts sources connecting to 4 destinations, which output to droppers (eventually). However when I try to connect a 5th source to the channel being shared by all those Tesseracts, it doesn't transfer.

Each source is marked as send only, and each destination is marked as receive only. When adding the 5th to the network, it doesn't find the receive destinations. If I mark one of the sources as send and receive, it will receive the items, and (I think) send them to the dropper-bound Tesseracts.

All that said, my question is: Does each send only Tesseract require a matching receive only tesseract, or do they all connect to the same channel and pull items as they are presented?

My goal with this setup was to have all my farms use the same channel, and output to my droppers (this is for a display water elevator that leads to an ImpuseSV style item sorter). However it looks to me like I will need to add a tesseract for each farm, which will cause bottlenecks as I progress.

**Comment by SuperMartijn642** [comment]
> Does each send only Tesseract require a matching receive only tesseract

The number of send only or receive only tesseracts does not matter. All tesseracts will send to/pull from all other tesseracts on the same channel.

> do they all connect to the same channel and pull items as they are presented?

Note that tesseracts themselves don't push or pull anything. Other things like hoppers, pipes, or machines can push to/pull from tesseracts and it is as if they're directly pushing to/pulling from blocks around other tesseracts on the same channel.
