### ISSUE TITLE
Tesseract break completely when break with hand in survival mode

### ISSUE THREAD

**Issue by LnX-OrioN** [SuperMartijn642/Tesseract#9]
Hi,
The tesseract breaks when it is picked up with the hand (left click) without tools in survival mode.
it is therefore unrecoverable and the materials are lost.

Tested on my modpack "Ascensio" on Curseforge 

Mc 1.12.2 with forge :14.23.5.2847

**Comment by SuperMartijn642** [comment]
Yes, that is the way it's supposed to work, you have to use a pickaxe to pick up a tesseract.

**Comment by LnX-OrioN** [comment]
ok, but i was surprised the first time this happened to me, i was thinking of a bug.
I don't remember that the Thermal Expansion one broke this way ...

It would be nice if you could add a config file to be able to disable this option.

Especially if we want to make the recipe much more expensive to make ^^

**Comment by SuperMartijn642** [comment]
I won't be adding a config option, since I feel the tesseract should be broken with a pickaxe. When you don't use a pickaxe, it takes a while to break the block just like vanilla blocks, like stone or a block of iron, which I feel is indicative enough.
In Thermal Expansion the tesseract could also only be picked up with either a pickaxe or by using a wrench.

**Comment by KiraLinux** [comment]
better completely remove the possibility of breaking the tesseract with your hand
I mean you can't break it by hand

**Comment by SuperMartijn642** [comment]
I just noticed that in the 1.12 version the tesseract breaks instantly when you punch it, because I forgot to set hardness and resistance values. Is that what you were talking about @LnX-OrioN ?

**Comment by SuperMartijn642** [comment]
I assume this is handled now.

**Comment by LnX-OrioN** [comment]
yes, exactly that's what i talking about ! Have you patched this issue ?

Le mer. 29 juil. 2020 à 09:30, SuperMartijn642 <notifications@github.com> a
écrit :

**Comment by SuperMartijn642** [comment]
Yes, then I did fix it at some point.
