### ISSUE TITLE
No transfer from end/nether to overworld

### ISSUE THREAD

**Issue by kraoc** [SuperMartijn642/Tesseract#90]
**Version Info**
- Minecraft, 1.20.4 (client & fabric server)
- Tesseract, 1.0.35

**Description of the Bug**
Using item transfert from nether or end to overworld seems to not function.

**Steps to Reproduce**

- Put a tesseract in nether/end with item send.
- Put a tesseract in overworld with item receive.
- No transfer from sender to receiver.

**Screenshots**
...

**Mods list on server**

- Automatic Operator
- Balm
- BlueMap
- BlueMap Offline Player Markers (Fabric)
- Collective
- Craft the Totem of Undying
- Double Doors
- Easy Craft Saddles
- Easy Diamond
- Easy Elytra Takeoff
- Easy Emerald
- Easy Netherite Ingot
- Essential Commands
- Explorer's Compass
- Fabric API
- Fabric Language Kotlin
- FabricProxy-Lite
- Inventory Totem
- Jade
- JourneyMap
- Mineral	Chance
- Name Tag Tweaks
- Nature's Compass
- Passive	Shield
- Plan | Player Analytics
- Replanting Crops
- Silk
- Starter Kit
- SuperMartijn642's Config Lib
- SuperMartijn642's Core Lib
- Tesseract
- Tree Harvester
- Universal Graves
- Veinminer
- Villager Names
- Villager Pickup
- Waystones
- Welcome Message
- WorldEdit

**Comment by SuperMartijn642** [comment]
Did you chunk load both areas? If one of the areas is unloaded, nothing will happen

**Comment by kraoc** [comment]
I tried a tp from one place to the other when transferring and see nothing happen...
It work on the overworld between dirrefent chunks point... If I see well :p
I'll try with a chunk loader mod... To see if it's the point !

**Comment by kraoc** [comment]
I used your Chunk Loader and it seems to work now... I need more testing and be back in some hours to confirm (or not) :p

**Comment by kraoc** [comment]
Seems resolved by using chunk loader... Sometimes connection seems lost but it's mainly functionnal.
Thanks!
