### ISSUE TITLE
compatibility with create

### ISSUE THREAD

**Issue by Carentmystic** [SuperMartijn642/Tesseract#91]
I don't know if it was me who didn't use the mod properly with the create, but when I try to apply some liquid or energy that involves the create, it ends up not working. I've tried to pass it as an entity, and in several ways, but none of them managed to transfer the liquid. I wanted to know if there is any way to transfer liquids and energy with create, or if the mod is not compatible with create.

**Comment by SuperMartijn642** [comment]
Can you share some screenshots of what your setup looks like?

**Comment by Carentmystic** [comment]
![2024-04-14_15 10 37](https://github.com/SuperMartijn642/Tesseract/assets/69648440/d62bff30-4530-42a9-b931-dab5302d7e2a)
![2024-04-14_15 16 29](https://github.com/SuperMartijn642/Tesseract/assets/69648440/5e512123-fd61-4516-bb41-e897865774a5)
![2024-04-14_15 08 47](https://github.com/SuperMartijn642/Tesseract/assets/69648440/8092879b-9b3e-40bd-bf3b-287cc51648a9)
![2024-04-14_15 10 26](https://github.com/SuperMartijn642/Tesseract/assets/69648440/576c427e-38b6-46cf-87ba-b24ef1106199)

**Comment by SuperMartijn642** [comment]
Just place one of the tesseracts directly against the tank.
When the pump pushes to/pulls from the tesseract, it directly pushes to/pulls from blocks around other tesseracts on the same channel. Most pipes don't allow pushing to them or pulling from them, thus having a pipe at both ends doesn't work.
