### ISSUE TITLE
[Bug] doesn't activate channel for items (any)

### ISSUE THREAD

**Issue by MehanikTMYT** [SuperMartijn642/Tesseract#95]
**Version Info**
- Minecraft, 1.20.4 neoforge
- Tesseract, 1.0.35

**Description of the Bug**
doesn't activate channel of items and sending items

**Steps to Reproduce**
open tesseract, create channel, try to activate

**Screenshots**
![image](https://github.com/SuperMartijn642/Tesseract/assets/29605858/92307c6f-5334-4070-a48a-35cc44feeb17)
activate 
![image](https://github.com/SuperMartijn642/Tesseract/assets/29605858/56d3968b-b888-402e-aff5-7970ae6a733e)
![image](https://github.com/SuperMartijn642/Tesseract/assets/29605858/391ffa5a-1132-46ee-9ab0-770175b7a7b3)
![image](https://github.com/SuperMartijn642/Tesseract/assets/29605858/66f872d2-773a-43fc-ac83-3a79cbb827d7)

energy channel work without problems

**Comment by SuperMartijn642** [comment]
Can you elaborate on what is not working? From your screenshots it looks like you can activate the channel fine.

**Comment by MehanikTMYT** [comment]
inactive channel
https://github.com/SuperMartijn642/Tesseract/assets/29605858/c2b2136c-d375-4075-b35d-51b4b1e6c06e

**Comment by SuperMartijn642** [comment]
What is the issue in that video?

**Comment by MehanikTMYT** [comment]
doesn't indicate status of channeles in time of first activate it in tesseract

**Comment by SuperMartijn642** [comment]
All types of channels seem to work to fine and show properly in the gui and in the Jade component. I cannot reproduce the issue you are showing in the video.
