### ISSUE TITLE
[Bug] Tesseract Channel

### ISSUE THREAD

**Issue by Nullble** [SuperMartijn642/Tesseract#97]
**Minecraft version**
- Minecraft, 1.12.2, Multiplayer server.
- Tesseract, 1.0.12
- Configlib-1.1-6
- Core-1.0.19

**Brief Description**
Channels become unusable, unselected, and unable to transmit. The tesseract will either show the channel there and not allow you to set the channel back, or it will then become unresponsive to deleting the old channel and require a brand-new one. The old channel will not be delectable unless the server restarts (Sometimes it does, sometimes it doesn't).

**How to replicate**
1) The first player crafts a Tesseract, it is then placed and a Unique (locked) channel is created and assigned.
2) The second player Follows step one,
3) ?, Potentially channels become erratic.

**Factors that might be playing into this:**
- The steps are followed but then a player then logs out with chunk loaders (IE2) or similar.
- The player just logs out and decides to freak out.
- Both players are potentially OP (Neither player in this instance is OP in this instance but have the ability to).
- A potential issue is that every time this happens one player hasn't been online when the other Tesseract was created & placed.
- Each instance Player One has locked channels, and Player Two created unlocked ones.

**Server settings that might be relevant:**
- online-mode=true
- prevent-proxy-connections=false

**Screenshots**

![ofVkFUsz3s](https://github.com/user-attachments/assets/3cf1717f-b982-4f4a-99d3-366952afad58)
![filezilla_nEuFWmiRIh](https://github.com/user-attachments/assets/54369e99-1927-4e1d-b8fe-147ab2306998)
![filezilla_NYWY2IL30z](https://github.com/user-attachments/assets/2f940882-ca84-4ed0-a199-ffdb8f02d115)

**Comment by SuperMartijn642** [comment]
You are using a version of Tesseract which is nearly 4 years old 🤔
