### ISSUE TITLE
[Feature] ... Increase the number of transfers?

### ISSUE THREAD

**Issue by QianMuu** [SuperMartijn642/Tesseract#98]
Is it possible to add a setting that can customize the amount of items transferred?

**Comment by SuperMartijn642** [comment]
I am unsure what you mean. The tesseract themselves don't transfer anything and they don't impose any limits on other blocks transferring items through them. The items transferred is purely dependent on the blocks pushing to/pulling from tesseracts

**Comment by yuk75** [comment]
How do you transfer through them? I set up hoppers and they do nothing

**Comment by SuperMartijn642** [comment]
@yuk75 please create a separate issue or join the discord and share some details about what you are trying to do.
