### ISSUE TITLE
[Crash] [20:11:09] Failed to encode packet 'clientbound/minecraft:custom_payload' (tesseract:main) 

### ISSUE THREAD

**Issue by Crazyminer34** [SuperMartijn642/Tesseract#99]
Minecraft 1.21.1
Tesseract 1.0.35+a
Fabric api 0.16.9

Crash log info:
https://mclo.gs/6ITxdtT

**Comment by Crazyminer34** [comment]
World is literally unplayable
all I did is name an energy channel with the character limit

**Comment by SuperMartijn642** [comment]
It seems like the server is sending a packet to update the available channels to the client. One of the channels somehow has a name with a length of 20 while the maximum length should be 19.

**Comment by Crazyminer34** [comment]
![image](https://github.com/user-attachments/assets/74116719-2b00-4684-96c3-36e8c136d535)

**Comment by Crazyminer34** [comment]
I changed the name and its fixed, so strange that it let me add an extra character tho
